import React from 'react';
import { StyleSheet, View, Text, Modal, TouchableOpacity, FlatList, Dimensions, Image, ScrollView } from 'react-native';

const { width, height } = Dimensions.get('window');
const ITEM_WIDTH = (width - 100) / 3;

const CATEGORIES = ['DIBUJOS', 'LETRAS', 'ZODIACO', 'EMOJIS', 'GYM', 'DEPORTES', 'PESAS', 'CALISTENIA', 'PILATES'];
export const STICKERS = [
  { id: 's1', image: require('../../../assets/stickers/AlienCabeza.png'), fileName: 'AlienCabeza.png', name: 'Alien Cabeza', category: 'CUSTOM' },
  { id: 's2', image: require('../../../assets/stickers/AnimalConejo.png'), fileName: 'AnimalConejo.png', name: 'Animal Conejo', category: 'CUSTOM' },
  { id: 's3', image: require('../../../assets/stickers/AnimalKoala.png'), fileName: 'AnimalKoala.png', name: 'Animal Koala', category: 'CUSTOM' },
  { id: 's4', image: require('../../../assets/stickers/AnimalLeon.png'), fileName: 'AnimalLeon.png', name: 'Animal Leon', category: 'CUSTOM' },
  { id: 's5', image: require('../../../assets/stickers/AnimalPanda.png'), fileName: 'AnimalPanda.png', name: 'Animal Panda', category: 'CUSTOM' },
  { id: 's6', image: require('../../../assets/stickers/Aries (2).png'), fileName: 'Aries (2).png', name: 'Aries ( 2)', category: 'CUSTOM' },
  { id: 's7', image: require('../../../assets/stickers/Cancer.png'), fileName: 'Cancer.png', name: 'Cancer', category: 'CUSTOM' },
  { id: 's8', image: require('../../../assets/stickers/Char_Arial_0.png'), fileName: 'Char_Arial_0.png', name: 'Letra 0 (Arial)', category: 'CUSTOM' },
  { id: 's9', image: require('../../../assets/stickers/Char_Arial_1.png'), fileName: 'Char_Arial_1.png', name: 'Letra 1 (Arial)', category: 'CUSTOM' },
  { id: 's10', image: require('../../../assets/stickers/Char_Arial_2.png'), fileName: 'Char_Arial_2.png', name: 'Letra 2 (Arial)', category: 'CUSTOM' },
  { id: 's11', image: require('../../../assets/stickers/Char_Arial_3.png'), fileName: 'Char_Arial_3.png', name: 'Letra 3 (Arial)', category: 'CUSTOM' },
  { id: 's12', image: require('../../../assets/stickers/Char_Arial_4.png'), fileName: 'Char_Arial_4.png', name: 'Letra 4 (Arial)', category: 'CUSTOM' },
  { id: 's13', image: require('../../../assets/stickers/Char_Arial_5.png'), fileName: 'Char_Arial_5.png', name: 'Letra 5 (Arial)', category: 'CUSTOM' },
  { id: 's14', image: require('../../../assets/stickers/Char_Arial_6.png'), fileName: 'Char_Arial_6.png', name: 'Letra 6 (Arial)', category: 'CUSTOM' },
  { id: 's15', image: require('../../../assets/stickers/Char_Arial_7.png'), fileName: 'Char_Arial_7.png', name: 'Letra 7 (Arial)', category: 'CUSTOM' },
  { id: 's16', image: require('../../../assets/stickers/Char_Arial_8.png'), fileName: 'Char_Arial_8.png', name: 'Letra 8 (Arial)', category: 'CUSTOM' },
  { id: 's17', image: require('../../../assets/stickers/Char_Arial_9.png'), fileName: 'Char_Arial_9.png', name: 'Letra 9 (Arial)', category: 'CUSTOM' },
  { id: 's18', image: require('../../../assets/stickers/Char_Arial_A.png'), fileName: 'Char_Arial_A.png', name: 'Letra A (Arial)', category: 'CUSTOM' },
  { id: 's19', image: require('../../../assets/stickers/Char_Arial_Asterisco.png'), fileName: 'Char_Arial_Asterisco.png', name: 'Letra Asterisco (Arial)', category: 'CUSTOM' },
  { id: 's20', image: require('../../../assets/stickers/Char_Arial_B.png'), fileName: 'Char_Arial_B.png', name: 'Letra B (Arial)', category: 'CUSTOM' },
  { id: 's21', image: require('../../../assets/stickers/Char_Arial_C.png'), fileName: 'Char_Arial_C.png', name: 'Letra C (Arial)', category: 'CUSTOM' },
  { id: 's22', image: require('../../../assets/stickers/Char_Arial_Coma.png'), fileName: 'Char_Arial_Coma.png', name: 'Letra Coma (Arial)', category: 'CUSTOM' },
  { id: 's23', image: require('../../../assets/stickers/Char_Arial_D.png'), fileName: 'Char_Arial_D.png', name: 'Letra D (Arial)', category: 'CUSTOM' },
  { id: 's24', image: require('../../../assets/stickers/Char_Arial_DosPuntos.png'), fileName: 'Char_Arial_DosPuntos.png', name: 'Letra DosPuntos (Arial)', category: 'CUSTOM' },
  { id: 's25', image: require('../../../assets/stickers/Char_Arial_E.png'), fileName: 'Char_Arial_E.png', name: 'Letra E (Arial)', category: 'CUSTOM' },
  { id: 's26', image: require('../../../assets/stickers/Char_Arial_Exclamacion.png'), fileName: 'Char_Arial_Exclamacion.png', name: 'Letra Exclamacion (Arial)', category: 'CUSTOM' },
  { id: 's27', image: require('../../../assets/stickers/Char_Arial_F.png'), fileName: 'Char_Arial_F.png', name: 'Letra F (Arial)', category: 'CUSTOM' },
  { id: 's28', image: require('../../../assets/stickers/Char_Arial_G.png'), fileName: 'Char_Arial_G.png', name: 'Letra G (Arial)', category: 'CUSTOM' },
  { id: 's29', image: require('../../../assets/stickers/Char_Arial_H.png'), fileName: 'Char_Arial_H.png', name: 'Letra H (Arial)', category: 'CUSTOM' },
  { id: 's30', image: require('../../../assets/stickers/Char_Arial_I.png'), fileName: 'Char_Arial_I.png', name: 'Letra I (Arial)', category: 'CUSTOM' },
  { id: 's31', image: require('../../../assets/stickers/Char_Arial_Igual.png'), fileName: 'Char_Arial_Igual.png', name: 'Letra Igual (Arial)', category: 'CUSTOM' },
  { id: 's32', image: require('../../../assets/stickers/Char_Arial_Interrogacion.png'), fileName: 'Char_Arial_Interrogacion.png', name: 'Letra Interrogacion (Arial)', category: 'CUSTOM' },
  { id: 's33', image: require('../../../assets/stickers/Char_Arial_J.png'), fileName: 'Char_Arial_J.png', name: 'Letra J (Arial)', category: 'CUSTOM' },
  { id: 's34', image: require('../../../assets/stickers/Char_Arial_K.png'), fileName: 'Char_Arial_K.png', name: 'Letra K (Arial)', category: 'CUSTOM' },
  { id: 's35', image: require('../../../assets/stickers/Char_Arial_L.png'), fileName: 'Char_Arial_L.png', name: 'Letra L (Arial)', category: 'CUSTOM' },
  { id: 's36', image: require('../../../assets/stickers/Char_Arial_M.png'), fileName: 'Char_Arial_M.png', name: 'Letra M (Arial)', category: 'CUSTOM' },
  { id: 's37', image: require('../../../assets/stickers/Char_Arial_Mas.png'), fileName: 'Char_Arial_Mas.png', name: 'Letra Mas (Arial)', category: 'CUSTOM' },
  { id: 's38', image: require('../../../assets/stickers/Char_Arial_Menos.png'), fileName: 'Char_Arial_Menos.png', name: 'Letra Menos (Arial)', category: 'CUSTOM' },
  { id: 's39', image: require('../../../assets/stickers/Char_Arial_N.png'), fileName: 'Char_Arial_N.png', name: 'Letra N (Arial)', category: 'CUSTOM' },
  { id: 's40', image: require('../../../assets/stickers/Char_Arial_O.png'), fileName: 'Char_Arial_O.png', name: 'Letra O (Arial)', category: 'CUSTOM' },
  { id: 's41', image: require('../../../assets/stickers/Char_Arial_P.png'), fileName: 'Char_Arial_P.png', name: 'Letra P (Arial)', category: 'CUSTOM' },
  { id: 's42', image: require('../../../assets/stickers/Char_Arial_Porcentaje.png'), fileName: 'Char_Arial_Porcentaje.png', name: 'Letra Porcentaje (Arial)', category: 'CUSTOM' },
  { id: 's43', image: require('../../../assets/stickers/Char_Arial_Punto.png'), fileName: 'Char_Arial_Punto.png', name: 'Letra Punto (Arial)', category: 'CUSTOM' },
  { id: 's44', image: require('../../../assets/stickers/Char_Arial_PuntoComa.png'), fileName: 'Char_Arial_PuntoComa.png', name: 'Letra PuntoComa (Arial)', category: 'CUSTOM' },
  { id: 's45', image: require('../../../assets/stickers/Char_Arial_Q.png'), fileName: 'Char_Arial_Q.png', name: 'Letra Q (Arial)', category: 'CUSTOM' },
  { id: 's46', image: require('../../../assets/stickers/Char_Arial_R.png'), fileName: 'Char_Arial_R.png', name: 'Letra R (Arial)', category: 'CUSTOM' },
  { id: 's47', image: require('../../../assets/stickers/Char_Arial_S.png'), fileName: 'Char_Arial_S.png', name: 'Letra S (Arial)', category: 'CUSTOM' },
  { id: 's48', image: require('../../../assets/stickers/Char_Arial_T.png'), fileName: 'Char_Arial_T.png', name: 'Letra T (Arial)', category: 'CUSTOM' },
  { id: 's49', image: require('../../../assets/stickers/Char_Arial_U.png'), fileName: 'Char_Arial_U.png', name: 'Letra U (Arial)', category: 'CUSTOM' },
  { id: 's50', image: require('../../../assets/stickers/Char_Arial_V.png'), fileName: 'Char_Arial_V.png', name: 'Letra V (Arial)', category: 'CUSTOM' },
  { id: 's51', image: require('../../../assets/stickers/Char_Arial_W.png'), fileName: 'Char_Arial_W.png', name: 'Letra W (Arial)', category: 'CUSTOM' },
  { id: 's52', image: require('../../../assets/stickers/Char_Arial_X.png'), fileName: 'Char_Arial_X.png', name: 'Letra X (Arial)', category: 'CUSTOM' },
  { id: 's53', image: require('../../../assets/stickers/Char_Arial_Y.png'), fileName: 'Char_Arial_Y.png', name: 'Letra Y (Arial)', category: 'CUSTOM' },
  { id: 's54', image: require('../../../assets/stickers/Char_Arial_Z.png'), fileName: 'Char_Arial_Z.png', name: 'Letra Z (Arial)', category: 'CUSTOM' },
  { id: 's55', image: require('../../../assets/stickers/Char_Comic_0.png'), fileName: 'Char_Comic_0.png', name: 'Letra 0 (Comic)', category: 'CUSTOM' },
  { id: 's56', image: require('../../../assets/stickers/Char_Comic_1.png'), fileName: 'Char_Comic_1.png', name: 'Letra 1 (Comic)', category: 'CUSTOM' },
  { id: 's57', image: require('../../../assets/stickers/Char_Comic_2.png'), fileName: 'Char_Comic_2.png', name: 'Letra 2 (Comic)', category: 'CUSTOM' },
  { id: 's58', image: require('../../../assets/stickers/Char_Comic_3.png'), fileName: 'Char_Comic_3.png', name: 'Letra 3 (Comic)', category: 'CUSTOM' },
  { id: 's59', image: require('../../../assets/stickers/Char_Comic_4.png'), fileName: 'Char_Comic_4.png', name: 'Letra 4 (Comic)', category: 'CUSTOM' },
  { id: 's60', image: require('../../../assets/stickers/Char_Comic_5.png'), fileName: 'Char_Comic_5.png', name: 'Letra 5 (Comic)', category: 'CUSTOM' },
  { id: 's61', image: require('../../../assets/stickers/Char_Comic_6.png'), fileName: 'Char_Comic_6.png', name: 'Letra 6 (Comic)', category: 'CUSTOM' },
  { id: 's62', image: require('../../../assets/stickers/Char_Comic_7.png'), fileName: 'Char_Comic_7.png', name: 'Letra 7 (Comic)', category: 'CUSTOM' },
  { id: 's63', image: require('../../../assets/stickers/Char_Comic_8.png'), fileName: 'Char_Comic_8.png', name: 'Letra 8 (Comic)', category: 'CUSTOM' },
  { id: 's64', image: require('../../../assets/stickers/Char_Comic_9.png'), fileName: 'Char_Comic_9.png', name: 'Letra 9 (Comic)', category: 'CUSTOM' },
  { id: 's65', image: require('../../../assets/stickers/Char_Comic_A.png'), fileName: 'Char_Comic_A.png', name: 'Letra A (Comic)', category: 'CUSTOM' },
  { id: 's66', image: require('../../../assets/stickers/Char_Comic_Asterisco.png'), fileName: 'Char_Comic_Asterisco.png', name: 'Letra Asterisco (Comic)', category: 'CUSTOM' },
  { id: 's67', image: require('../../../assets/stickers/Char_Comic_B.png'), fileName: 'Char_Comic_B.png', name: 'Letra B (Comic)', category: 'CUSTOM' },
  { id: 's68', image: require('../../../assets/stickers/Char_Comic_C.png'), fileName: 'Char_Comic_C.png', name: 'Letra C (Comic)', category: 'CUSTOM' },
  { id: 's69', image: require('../../../assets/stickers/Char_Comic_Coma.png'), fileName: 'Char_Comic_Coma.png', name: 'Letra Coma (Comic)', category: 'CUSTOM' },
  { id: 's70', image: require('../../../assets/stickers/Char_Comic_D.png'), fileName: 'Char_Comic_D.png', name: 'Letra D (Comic)', category: 'CUSTOM' },
  { id: 's71', image: require('../../../assets/stickers/Char_Comic_DosPuntos.png'), fileName: 'Char_Comic_DosPuntos.png', name: 'Letra DosPuntos (Comic)', category: 'CUSTOM' },
  { id: 's72', image: require('../../../assets/stickers/Char_Comic_E.png'), fileName: 'Char_Comic_E.png', name: 'Letra E (Comic)', category: 'CUSTOM' },
  { id: 's73', image: require('../../../assets/stickers/Char_Comic_Exclamacion.png'), fileName: 'Char_Comic_Exclamacion.png', name: 'Letra Exclamacion (Comic)', category: 'CUSTOM' },
  { id: 's74', image: require('../../../assets/stickers/Char_Comic_F.png'), fileName: 'Char_Comic_F.png', name: 'Letra F (Comic)', category: 'CUSTOM' },
  { id: 's75', image: require('../../../assets/stickers/Char_Comic_G.png'), fileName: 'Char_Comic_G.png', name: 'Letra G (Comic)', category: 'CUSTOM' },
  { id: 's76', image: require('../../../assets/stickers/Char_Comic_H.png'), fileName: 'Char_Comic_H.png', name: 'Letra H (Comic)', category: 'CUSTOM' },
  { id: 's77', image: require('../../../assets/stickers/Char_Comic_I.png'), fileName: 'Char_Comic_I.png', name: 'Letra I (Comic)', category: 'CUSTOM' },
  { id: 's78', image: require('../../../assets/stickers/Char_Comic_Igual.png'), fileName: 'Char_Comic_Igual.png', name: 'Letra Igual (Comic)', category: 'CUSTOM' },
  { id: 's79', image: require('../../../assets/stickers/Char_Comic_Interrogacion.png'), fileName: 'Char_Comic_Interrogacion.png', name: 'Letra Interrogacion (Comic)', category: 'CUSTOM' },
  { id: 's80', image: require('../../../assets/stickers/Char_Comic_J.png'), fileName: 'Char_Comic_J.png', name: 'Letra J (Comic)', category: 'CUSTOM' },
  { id: 's81', image: require('../../../assets/stickers/Char_Comic_K.png'), fileName: 'Char_Comic_K.png', name: 'Letra K (Comic)', category: 'CUSTOM' },
  { id: 's82', image: require('../../../assets/stickers/Char_Comic_L.png'), fileName: 'Char_Comic_L.png', name: 'Letra L (Comic)', category: 'CUSTOM' },
  { id: 's83', image: require('../../../assets/stickers/Char_Comic_M.png'), fileName: 'Char_Comic_M.png', name: 'Letra M (Comic)', category: 'CUSTOM' },
  { id: 's84', image: require('../../../assets/stickers/Char_Comic_Mas.png'), fileName: 'Char_Comic_Mas.png', name: 'Letra Mas (Comic)', category: 'CUSTOM' },
  { id: 's85', image: require('../../../assets/stickers/Char_Comic_Menos.png'), fileName: 'Char_Comic_Menos.png', name: 'Letra Menos (Comic)', category: 'CUSTOM' },
  { id: 's86', image: require('../../../assets/stickers/Char_Comic_N.png'), fileName: 'Char_Comic_N.png', name: 'Letra N (Comic)', category: 'CUSTOM' },
  { id: 's87', image: require('../../../assets/stickers/Char_Comic_O.png'), fileName: 'Char_Comic_O.png', name: 'Letra O (Comic)', category: 'CUSTOM' },
  { id: 's88', image: require('../../../assets/stickers/Char_Comic_P.png'), fileName: 'Char_Comic_P.png', name: 'Letra P (Comic)', category: 'CUSTOM' },
  { id: 's89', image: require('../../../assets/stickers/Char_Comic_Porcentaje.png'), fileName: 'Char_Comic_Porcentaje.png', name: 'Letra Porcentaje (Comic)', category: 'CUSTOM' },
  { id: 's90', image: require('../../../assets/stickers/Char_Comic_Punto.png'), fileName: 'Char_Comic_Punto.png', name: 'Letra Punto (Comic)', category: 'CUSTOM' },
  { id: 's91', image: require('../../../assets/stickers/Char_Comic_PuntoComa.png'), fileName: 'Char_Comic_PuntoComa.png', name: 'Letra PuntoComa (Comic)', category: 'CUSTOM' },
  { id: 's92', image: require('../../../assets/stickers/Char_Comic_Q.png'), fileName: 'Char_Comic_Q.png', name: 'Letra Q (Comic)', category: 'CUSTOM' },
  { id: 's93', image: require('../../../assets/stickers/Char_Comic_R.png'), fileName: 'Char_Comic_R.png', name: 'Letra R (Comic)', category: 'CUSTOM' },
  { id: 's94', image: require('../../../assets/stickers/Char_Comic_S.png'), fileName: 'Char_Comic_S.png', name: 'Letra S (Comic)', category: 'CUSTOM' },
  { id: 's95', image: require('../../../assets/stickers/Char_Comic_T.png'), fileName: 'Char_Comic_T.png', name: 'Letra T (Comic)', category: 'CUSTOM' },
  { id: 's96', image: require('../../../assets/stickers/Char_Comic_U.png'), fileName: 'Char_Comic_U.png', name: 'Letra U (Comic)', category: 'CUSTOM' },
  { id: 's97', image: require('../../../assets/stickers/Char_Comic_V.png'), fileName: 'Char_Comic_V.png', name: 'Letra V (Comic)', category: 'CUSTOM' },
  { id: 's98', image: require('../../../assets/stickers/Char_Comic_W.png'), fileName: 'Char_Comic_W.png', name: 'Letra W (Comic)', category: 'CUSTOM' },
  { id: 's99', image: require('../../../assets/stickers/Char_Comic_X.png'), fileName: 'Char_Comic_X.png', name: 'Letra X (Comic)', category: 'CUSTOM' },
  { id: 's100', image: require('../../../assets/stickers/Char_Comic_Y.png'), fileName: 'Char_Comic_Y.png', name: 'Letra Y (Comic)', category: 'CUSTOM' },
  { id: 's101', image: require('../../../assets/stickers/Char_Comic_Z.png'), fileName: 'Char_Comic_Z.png', name: 'Letra Z (Comic)', category: 'CUSTOM' },
  { id: 's102', image: require('../../../assets/stickers/Char_Georgia_0.png'), fileName: 'Char_Georgia_0.png', name: 'Letra 0 (Georgia)', category: 'CUSTOM' },
  { id: 's103', image: require('../../../assets/stickers/Char_Georgia_1.png'), fileName: 'Char_Georgia_1.png', name: 'Letra 1 (Georgia)', category: 'CUSTOM' },
  { id: 's104', image: require('../../../assets/stickers/Char_Georgia_2.png'), fileName: 'Char_Georgia_2.png', name: 'Letra 2 (Georgia)', category: 'CUSTOM' },
  { id: 's105', image: require('../../../assets/stickers/Char_Georgia_3.png'), fileName: 'Char_Georgia_3.png', name: 'Letra 3 (Georgia)', category: 'CUSTOM' },
  { id: 's106', image: require('../../../assets/stickers/Char_Georgia_4.png'), fileName: 'Char_Georgia_4.png', name: 'Letra 4 (Georgia)', category: 'CUSTOM' },
  { id: 's107', image: require('../../../assets/stickers/Char_Georgia_5.png'), fileName: 'Char_Georgia_5.png', name: 'Letra 5 (Georgia)', category: 'CUSTOM' },
  { id: 's108', image: require('../../../assets/stickers/Char_Georgia_6.png'), fileName: 'Char_Georgia_6.png', name: 'Letra 6 (Georgia)', category: 'CUSTOM' },
  { id: 's109', image: require('../../../assets/stickers/Char_Georgia_7.png'), fileName: 'Char_Georgia_7.png', name: 'Letra 7 (Georgia)', category: 'CUSTOM' },
  { id: 's110', image: require('../../../assets/stickers/Char_Georgia_8.png'), fileName: 'Char_Georgia_8.png', name: 'Letra 8 (Georgia)', category: 'CUSTOM' },
  { id: 's111', image: require('../../../assets/stickers/Char_Georgia_9.png'), fileName: 'Char_Georgia_9.png', name: 'Letra 9 (Georgia)', category: 'CUSTOM' },
  { id: 's112', image: require('../../../assets/stickers/Char_Georgia_A.png'), fileName: 'Char_Georgia_A.png', name: 'Letra A (Georgia)', category: 'CUSTOM' },
  { id: 's113', image: require('../../../assets/stickers/Char_Georgia_Asterisco.png'), fileName: 'Char_Georgia_Asterisco.png', name: 'Letra Asterisco (Georgia)', category: 'CUSTOM' },
  { id: 's114', image: require('../../../assets/stickers/Char_Georgia_B.png'), fileName: 'Char_Georgia_B.png', name: 'Letra B (Georgia)', category: 'CUSTOM' },
  { id: 's115', image: require('../../../assets/stickers/Char_Georgia_C.png'), fileName: 'Char_Georgia_C.png', name: 'Letra C (Georgia)', category: 'CUSTOM' },
  { id: 's116', image: require('../../../assets/stickers/Char_Georgia_Coma.png'), fileName: 'Char_Georgia_Coma.png', name: 'Letra Coma (Georgia)', category: 'CUSTOM' },
  { id: 's117', image: require('../../../assets/stickers/Char_Georgia_D.png'), fileName: 'Char_Georgia_D.png', name: 'Letra D (Georgia)', category: 'CUSTOM' },
  { id: 's118', image: require('../../../assets/stickers/Char_Georgia_DosPuntos.png'), fileName: 'Char_Georgia_DosPuntos.png', name: 'Letra DosPuntos (Georgia)', category: 'CUSTOM' },
  { id: 's119', image: require('../../../assets/stickers/Char_Georgia_E.png'), fileName: 'Char_Georgia_E.png', name: 'Letra E (Georgia)', category: 'CUSTOM' },
  { id: 's120', image: require('../../../assets/stickers/Char_Georgia_Exclamacion.png'), fileName: 'Char_Georgia_Exclamacion.png', name: 'Letra Exclamacion (Georgia)', category: 'CUSTOM' },
  { id: 's121', image: require('../../../assets/stickers/Char_Georgia_F.png'), fileName: 'Char_Georgia_F.png', name: 'Letra F (Georgia)', category: 'CUSTOM' },
  { id: 's122', image: require('../../../assets/stickers/Char_Georgia_G.png'), fileName: 'Char_Georgia_G.png', name: 'Letra G (Georgia)', category: 'CUSTOM' },
  { id: 's123', image: require('../../../assets/stickers/Char_Georgia_H.png'), fileName: 'Char_Georgia_H.png', name: 'Letra H (Georgia)', category: 'CUSTOM' },
  { id: 's124', image: require('../../../assets/stickers/Char_Georgia_I.png'), fileName: 'Char_Georgia_I.png', name: 'Letra I (Georgia)', category: 'CUSTOM' },
  { id: 's125', image: require('../../../assets/stickers/Char_Georgia_Igual.png'), fileName: 'Char_Georgia_Igual.png', name: 'Letra Igual (Georgia)', category: 'CUSTOM' },
  { id: 's126', image: require('../../../assets/stickers/Char_Georgia_Interrogacion.png'), fileName: 'Char_Georgia_Interrogacion.png', name: 'Letra Interrogacion (Georgia)', category: 'CUSTOM' },
  { id: 's127', image: require('../../../assets/stickers/Char_Georgia_J.png'), fileName: 'Char_Georgia_J.png', name: 'Letra J (Georgia)', category: 'CUSTOM' },
  { id: 's128', image: require('../../../assets/stickers/Char_Georgia_K.png'), fileName: 'Char_Georgia_K.png', name: 'Letra K (Georgia)', category: 'CUSTOM' },
  { id: 's129', image: require('../../../assets/stickers/Char_Georgia_L.png'), fileName: 'Char_Georgia_L.png', name: 'Letra L (Georgia)', category: 'CUSTOM' },
  { id: 's130', image: require('../../../assets/stickers/Char_Georgia_M.png'), fileName: 'Char_Georgia_M.png', name: 'Letra M (Georgia)', category: 'CUSTOM' },
  { id: 's131', image: require('../../../assets/stickers/Char_Georgia_Mas.png'), fileName: 'Char_Georgia_Mas.png', name: 'Letra Mas (Georgia)', category: 'CUSTOM' },
  { id: 's132', image: require('../../../assets/stickers/Char_Georgia_Menos.png'), fileName: 'Char_Georgia_Menos.png', name: 'Letra Menos (Georgia)', category: 'CUSTOM' },
  { id: 's133', image: require('../../../assets/stickers/Char_Georgia_N.png'), fileName: 'Char_Georgia_N.png', name: 'Letra N (Georgia)', category: 'CUSTOM' },
  { id: 's134', image: require('../../../assets/stickers/Char_Georgia_O.png'), fileName: 'Char_Georgia_O.png', name: 'Letra O (Georgia)', category: 'CUSTOM' },
  { id: 's135', image: require('../../../assets/stickers/Char_Georgia_P.png'), fileName: 'Char_Georgia_P.png', name: 'Letra P (Georgia)', category: 'CUSTOM' },
  { id: 's136', image: require('../../../assets/stickers/Char_Georgia_Porcentaje.png'), fileName: 'Char_Georgia_Porcentaje.png', name: 'Letra Porcentaje (Georgia)', category: 'CUSTOM' },
  { id: 's137', image: require('../../../assets/stickers/Char_Georgia_Punto.png'), fileName: 'Char_Georgia_Punto.png', name: 'Letra Punto (Georgia)', category: 'CUSTOM' },
  { id: 's138', image: require('../../../assets/stickers/Char_Georgia_PuntoComa.png'), fileName: 'Char_Georgia_PuntoComa.png', name: 'Letra PuntoComa (Georgia)', category: 'CUSTOM' },
  { id: 's139', image: require('../../../assets/stickers/Char_Georgia_Q.png'), fileName: 'Char_Georgia_Q.png', name: 'Letra Q (Georgia)', category: 'CUSTOM' },
  { id: 's140', image: require('../../../assets/stickers/Char_Georgia_R.png'), fileName: 'Char_Georgia_R.png', name: 'Letra R (Georgia)', category: 'CUSTOM' },
  { id: 's141', image: require('../../../assets/stickers/Char_Georgia_S.png'), fileName: 'Char_Georgia_S.png', name: 'Letra S (Georgia)', category: 'CUSTOM' },
  { id: 's142', image: require('../../../assets/stickers/Char_Georgia_T.png'), fileName: 'Char_Georgia_T.png', name: 'Letra T (Georgia)', category: 'CUSTOM' },
  { id: 's143', image: require('../../../assets/stickers/Char_Georgia_U.png'), fileName: 'Char_Georgia_U.png', name: 'Letra U (Georgia)', category: 'CUSTOM' },
  { id: 's144', image: require('../../../assets/stickers/Char_Georgia_V.png'), fileName: 'Char_Georgia_V.png', name: 'Letra V (Georgia)', category: 'CUSTOM' },
  { id: 's145', image: require('../../../assets/stickers/Char_Georgia_W.png'), fileName: 'Char_Georgia_W.png', name: 'Letra W (Georgia)', category: 'CUSTOM' },
  { id: 's146', image: require('../../../assets/stickers/Char_Georgia_X.png'), fileName: 'Char_Georgia_X.png', name: 'Letra X (Georgia)', category: 'CUSTOM' },
  { id: 's147', image: require('../../../assets/stickers/Char_Georgia_Y.png'), fileName: 'Char_Georgia_Y.png', name: 'Letra Y (Georgia)', category: 'CUSTOM' },
  { id: 's148', image: require('../../../assets/stickers/Char_Georgia_Z.png'), fileName: 'Char_Georgia_Z.png', name: 'Letra Z (Georgia)', category: 'CUSTOM' },
  { id: 's149', image: require('../../../assets/stickers/Char_Impact_0.png'), fileName: 'Char_Impact_0.png', name: 'Letra 0 (Impact)', category: 'CUSTOM' },
  { id: 's150', image: require('../../../assets/stickers/Char_Impact_1.png'), fileName: 'Char_Impact_1.png', name: 'Letra 1 (Impact)', category: 'CUSTOM' },
  { id: 's151', image: require('../../../assets/stickers/Char_Impact_2.png'), fileName: 'Char_Impact_2.png', name: 'Letra 2 (Impact)', category: 'CUSTOM' },
  { id: 's152', image: require('../../../assets/stickers/Char_Impact_3.png'), fileName: 'Char_Impact_3.png', name: 'Letra 3 (Impact)', category: 'CUSTOM' },
  { id: 's153', image: require('../../../assets/stickers/Char_Impact_4.png'), fileName: 'Char_Impact_4.png', name: 'Letra 4 (Impact)', category: 'CUSTOM' },
  { id: 's154', image: require('../../../assets/stickers/Char_Impact_5.png'), fileName: 'Char_Impact_5.png', name: 'Letra 5 (Impact)', category: 'CUSTOM' },
  { id: 's155', image: require('../../../assets/stickers/Char_Impact_6.png'), fileName: 'Char_Impact_6.png', name: 'Letra 6 (Impact)', category: 'CUSTOM' },
  { id: 's156', image: require('../../../assets/stickers/Char_Impact_7.png'), fileName: 'Char_Impact_7.png', name: 'Letra 7 (Impact)', category: 'CUSTOM' },
  { id: 's157', image: require('../../../assets/stickers/Char_Impact_8.png'), fileName: 'Char_Impact_8.png', name: 'Letra 8 (Impact)', category: 'CUSTOM' },
  { id: 's158', image: require('../../../assets/stickers/Char_Impact_9.png'), fileName: 'Char_Impact_9.png', name: 'Letra 9 (Impact)', category: 'CUSTOM' },
  { id: 's159', image: require('../../../assets/stickers/Char_Impact_A.png'), fileName: 'Char_Impact_A.png', name: 'Letra A (Impact)', category: 'CUSTOM' },
  { id: 's160', image: require('../../../assets/stickers/Char_Impact_Asterisco.png'), fileName: 'Char_Impact_Asterisco.png', name: 'Letra Asterisco (Impact)', category: 'CUSTOM' },
  { id: 's161', image: require('../../../assets/stickers/Char_Impact_B.png'), fileName: 'Char_Impact_B.png', name: 'Letra B (Impact)', category: 'CUSTOM' },
  { id: 's162', image: require('../../../assets/stickers/Char_Impact_C.png'), fileName: 'Char_Impact_C.png', name: 'Letra C (Impact)', category: 'CUSTOM' },
  { id: 's163', image: require('../../../assets/stickers/Char_Impact_Coma.png'), fileName: 'Char_Impact_Coma.png', name: 'Letra Coma (Impact)', category: 'CUSTOM' },
  { id: 's164', image: require('../../../assets/stickers/Char_Impact_D.png'), fileName: 'Char_Impact_D.png', name: 'Letra D (Impact)', category: 'CUSTOM' },
  { id: 's165', image: require('../../../assets/stickers/Char_Impact_DosPuntos.png'), fileName: 'Char_Impact_DosPuntos.png', name: 'Letra DosPuntos (Impact)', category: 'CUSTOM' },
  { id: 's166', image: require('../../../assets/stickers/Char_Impact_E.png'), fileName: 'Char_Impact_E.png', name: 'Letra E (Impact)', category: 'CUSTOM' },
  { id: 's167', image: require('../../../assets/stickers/Char_Impact_Exclamacion.png'), fileName: 'Char_Impact_Exclamacion.png', name: 'Letra Exclamacion (Impact)', category: 'CUSTOM' },
  { id: 's168', image: require('../../../assets/stickers/Char_Impact_F.png'), fileName: 'Char_Impact_F.png', name: 'Letra F (Impact)', category: 'CUSTOM' },
  { id: 's169', image: require('../../../assets/stickers/Char_Impact_G.png'), fileName: 'Char_Impact_G.png', name: 'Letra G (Impact)', category: 'CUSTOM' },
  { id: 's170', image: require('../../../assets/stickers/Char_Impact_H.png'), fileName: 'Char_Impact_H.png', name: 'Letra H (Impact)', category: 'CUSTOM' },
  { id: 's171', image: require('../../../assets/stickers/Char_Impact_I.png'), fileName: 'Char_Impact_I.png', name: 'Letra I (Impact)', category: 'CUSTOM' },
  { id: 's172', image: require('../../../assets/stickers/Char_Impact_Igual.png'), fileName: 'Char_Impact_Igual.png', name: 'Letra Igual (Impact)', category: 'CUSTOM' },
  { id: 's173', image: require('../../../assets/stickers/Char_Impact_Interrogacion.png'), fileName: 'Char_Impact_Interrogacion.png', name: 'Letra Interrogacion (Impact)', category: 'CUSTOM' },
  { id: 's174', image: require('../../../assets/stickers/Char_Impact_J.png'), fileName: 'Char_Impact_J.png', name: 'Letra J (Impact)', category: 'CUSTOM' },
  { id: 's175', image: require('../../../assets/stickers/Char_Impact_K.png'), fileName: 'Char_Impact_K.png', name: 'Letra K (Impact)', category: 'CUSTOM' },
  { id: 's176', image: require('../../../assets/stickers/Char_Impact_L.png'), fileName: 'Char_Impact_L.png', name: 'Letra L (Impact)', category: 'CUSTOM' },
  { id: 's177', image: require('../../../assets/stickers/Char_Impact_M.png'), fileName: 'Char_Impact_M.png', name: 'Letra M (Impact)', category: 'CUSTOM' },
  { id: 's178', image: require('../../../assets/stickers/Char_Impact_Mas.png'), fileName: 'Char_Impact_Mas.png', name: 'Letra Mas (Impact)', category: 'CUSTOM' },
  { id: 's179', image: require('../../../assets/stickers/Char_Impact_Menos.png'), fileName: 'Char_Impact_Menos.png', name: 'Letra Menos (Impact)', category: 'CUSTOM' },
  { id: 's180', image: require('../../../assets/stickers/Char_Impact_N.png'), fileName: 'Char_Impact_N.png', name: 'Letra N (Impact)', category: 'CUSTOM' },
  { id: 's181', image: require('../../../assets/stickers/Char_Impact_O.png'), fileName: 'Char_Impact_O.png', name: 'Letra O (Impact)', category: 'CUSTOM' },
  { id: 's182', image: require('../../../assets/stickers/Char_Impact_P.png'), fileName: 'Char_Impact_P.png', name: 'Letra P (Impact)', category: 'CUSTOM' },
  { id: 's183', image: require('../../../assets/stickers/Char_Impact_Porcentaje.png'), fileName: 'Char_Impact_Porcentaje.png', name: 'Letra Porcentaje (Impact)', category: 'CUSTOM' },
  { id: 's184', image: require('../../../assets/stickers/Char_Impact_Punto.png'), fileName: 'Char_Impact_Punto.png', name: 'Letra Punto (Impact)', category: 'CUSTOM' },
  { id: 's185', image: require('../../../assets/stickers/Char_Impact_PuntoComa.png'), fileName: 'Char_Impact_PuntoComa.png', name: 'Letra PuntoComa (Impact)', category: 'CUSTOM' },
  { id: 's186', image: require('../../../assets/stickers/Char_Impact_Q.png'), fileName: 'Char_Impact_Q.png', name: 'Letra Q (Impact)', category: 'CUSTOM' },
  { id: 's187', image: require('../../../assets/stickers/Char_Impact_R.png'), fileName: 'Char_Impact_R.png', name: 'Letra R (Impact)', category: 'CUSTOM' },
  { id: 's188', image: require('../../../assets/stickers/Char_Impact_S.png'), fileName: 'Char_Impact_S.png', name: 'Letra S (Impact)', category: 'CUSTOM' },
  { id: 's189', image: require('../../../assets/stickers/Char_Impact_T.png'), fileName: 'Char_Impact_T.png', name: 'Letra T (Impact)', category: 'CUSTOM' },
  { id: 's190', image: require('../../../assets/stickers/Char_Impact_U.png'), fileName: 'Char_Impact_U.png', name: 'Letra U (Impact)', category: 'CUSTOM' },
  { id: 's191', image: require('../../../assets/stickers/Char_Impact_V.png'), fileName: 'Char_Impact_V.png', name: 'Letra V (Impact)', category: 'CUSTOM' },
  { id: 's192', image: require('../../../assets/stickers/Char_Impact_W.png'), fileName: 'Char_Impact_W.png', name: 'Letra W (Impact)', category: 'CUSTOM' },
  { id: 's193', image: require('../../../assets/stickers/Char_Impact_X.png'), fileName: 'Char_Impact_X.png', name: 'Letra X (Impact)', category: 'CUSTOM' },
  { id: 's194', image: require('../../../assets/stickers/Char_Impact_Y.png'), fileName: 'Char_Impact_Y.png', name: 'Letra Y (Impact)', category: 'CUSTOM' },
  { id: 's195', image: require('../../../assets/stickers/Char_Impact_Z.png'), fileName: 'Char_Impact_Z.png', name: 'Letra Z (Impact)', category: 'CUSTOM' },
  { id: 's196', image: require('../../../assets/stickers/ComidaDona.png'), fileName: 'ComidaDona.png', name: 'Comida Dona', category: 'CUSTOM' },
  { id: 's197', image: require('../../../assets/stickers/ComidaHamburguesa.png'), fileName: 'ComidaHamburguesa.png', name: 'Comida Hamburguesa', category: 'CUSTOM' },
  { id: 's198', image: require('../../../assets/stickers/ComidaPizzaRebanada.png'), fileName: 'ComidaPizzaRebanada.png', name: 'Comida Pizza Rebanada', category: 'CUSTOM' },
  { id: 's199', image: require('../../../assets/stickers/CorazonPixeladaRoja.png'), fileName: 'CorazonPixeladaRoja.png', name: 'Corazon Pixelada Roja', category: 'CUSTOM' },
  { id: 's200', image: require('../../../assets/stickers/CorazonRosaPixelado.png'), fileName: 'CorazonRosaPixelado.png', name: 'Corazon Rosa Pixelado', category: 'CUSTOM' },
  { id: 's201', image: require('../../../assets/stickers/EmojiBandera.png'), fileName: 'EmojiBandera.png', name: 'Emoji Bandera', category: 'CUSTOM' },
  { id: 's202', image: require('../../../assets/stickers/EmojiCohete.png'), fileName: 'EmojiCohete.png', name: 'Emoji Cohete', category: 'CUSTOM' },
  { id: 's203', image: require('../../../assets/stickers/EmojiCorazon.png'), fileName: 'EmojiCorazon.png', name: 'Emoji Corazon', category: 'CUSTOM' },
  { id: 's204', image: require('../../../assets/stickers/EmojiFuego.png'), fileName: 'EmojiFuego.png', name: 'Emoji Fuego', category: 'CUSTOM' },
  { id: 's205', image: require('../../../assets/stickers/EmojiNubeLluvia.png'), fileName: 'EmojiNubeLluvia.png', name: 'Emoji Nube Lluvia', category: 'CUSTOM' },
  { id: 's206', image: require('../../../assets/stickers/EmojiRayo.png'), fileName: 'EmojiRayo.png', name: 'Emoji Rayo', category: 'CUSTOM' },
  { id: 's207', image: require('../../../assets/stickers/EmojiSol.png'), fileName: 'EmojiSol.png', name: 'Emoji Sol', category: 'CUSTOM' },
  { id: 's208', image: require('../../../assets/stickers/EspacioAstronauta.png'), fileName: 'EspacioAstronauta.png', name: 'Espacio Astronauta', category: 'CUSTOM' },
  { id: 's209', image: require('../../../assets/stickers/EspacioOvni.png'), fileName: 'EspacioOvni.png', name: 'Espacio Ovni', category: 'CUSTOM' },
  { id: 's210', image: require('../../../assets/stickers/EspacioSaturno.png'), fileName: 'EspacioSaturno.png', name: 'Espacio Saturno', category: 'CUSTOM' },
  { id: 's211', image: require('../../../assets/stickers/Frutilla.png'), fileName: 'Frutilla.png', name: 'Frutilla', category: 'CUSTOM' },
  { id: 's212', image: require('../../../assets/stickers/GatoVector.png'), fileName: 'GatoVector.png', name: 'Gato Vector', category: 'CUSTOM' },
  { id: 's213', image: require('../../../assets/stickers/Geminis.png'), fileName: 'Geminis.png', name: 'Geminis', category: 'CUSTOM' },
  { id: 's214', image: require('../../../assets/stickers/Leo.png'), fileName: 'Leo.png', name: 'Leo', category: 'CUSTOM' },
  { id: 's215', image: require('../../../assets/stickers/Luna1.png'), fileName: 'Luna1.png', name: 'Luna 1', category: 'CUSTOM' },
  { id: 's216', image: require('../../../assets/stickers/Mariposa2.png'), fileName: 'Mariposa2.png', name: 'Mariposa 2', category: 'CUSTOM' },
  { id: 's217', image: require('../../../assets/stickers/MemeDoge.png'), fileName: 'MemeDoge.png', name: 'Meme Doge', category: 'CUSTOM' },
  { id: 's218', image: require('../../../assets/stickers/MemeSapoTriste.png'), fileName: 'MemeSapoTriste.png', name: 'Meme Sapo Triste', category: 'CUSTOM' },
  { id: 's219', image: require('../../../assets/stickers/MemeStonks.png'), fileName: 'MemeStonks.png', name: 'Meme Stonks', category: 'CUSTOM' },
  { id: 's220', image: require('../../../assets/stickers/MemeTroll.png'), fileName: 'MemeTroll.png', name: 'Meme Troll', category: 'CUSTOM' },
  { id: 's221', image: require('../../../assets/stickers/MonumentoColiseo.png'), fileName: 'MonumentoColiseo.png', name: 'Monumento Coliseo', category: 'CUSTOM' },
  { id: 's222', image: require('../../../assets/stickers/MonumentoEiffel.png'), fileName: 'MonumentoEiffel.png', name: 'Monumento Eiffel', category: 'CUSTOM' },
  { id: 's223', image: require('../../../assets/stickers/MonumentoPiramides.png'), fileName: 'MonumentoPiramides.png', name: 'Monumento Piramides', category: 'CUSTOM' },
  { id: 's224', image: require('../../../assets/stickers/MonumentoTorrePisa.png'), fileName: 'MonumentoTorrePisa.png', name: 'Monumento Torre Pisa', category: 'CUSTOM' },
  { id: 's225', image: require('../../../assets/stickers/NaturalezaHongo.png'), fileName: 'NaturalezaHongo.png', name: 'Naturaleza Hongo', category: 'CUSTOM' },
  { id: 's226', image: require('../../../assets/stickers/ObjetoCamara.png'), fileName: 'ObjetoCamara.png', name: 'Objeto Camara', category: 'CUSTOM' },
  { id: 's227', image: require('../../../assets/stickers/ObjetoCassette.png'), fileName: 'ObjetoCassette.png', name: 'Objeto Cassette', category: 'CUSTOM' },
  { id: 's228', image: require('../../../assets/stickers/ObjetoCorona.png'), fileName: 'ObjetoCorona.png', name: 'Objeto Corona', category: 'CUSTOM' },
  { id: 's229', image: require('../../../assets/stickers/ObjetoDiamante.png'), fileName: 'ObjetoDiamante.png', name: 'Objeto Diamante', category: 'CUSTOM' },
  { id: 's230', image: require('../../../assets/stickers/ObjetoLamparita.png'), fileName: 'ObjetoLamparita.png', name: 'Objeto Lamparita', category: 'CUSTOM' },
  { id: 's231', image: require('../../../assets/stickers/ObjetoLapiz.png'), fileName: 'ObjetoLapiz.png', name: 'Objeto Lapiz', category: 'CUSTOM' },
  { id: 's232', image: require('../../../assets/stickers/ObjetoLlave.png'), fileName: 'ObjetoLlave.png', name: 'Objeto Llave', category: 'CUSTOM' },
  { id: 's233', image: require('../../../assets/stickers/ObjetoMate.png'), fileName: 'ObjetoMate.png', name: 'Objeto Mate', category: 'CUSTOM' },
  { id: 's234', image: require('../../../assets/stickers/ObjetoTaza.png'), fileName: 'ObjetoTaza.png', name: 'Objeto Taza', category: 'CUSTOM' },
  { id: 's235', image: require('../../../assets/stickers/ObjetoTrofeo.png'), fileName: 'ObjetoTrofeo.png', name: 'Objeto Trofeo', category: 'CUSTOM' },
  { id: 's236', image: require('../../../assets/stickers/PaisajeAtardecerMar.png'), fileName: 'PaisajeAtardecerMar.png', name: 'Paisaje Atardecer Mar', category: 'CUSTOM' },
  { id: 's237', image: require('../../../assets/stickers/PaisajeBosque.png'), fileName: 'PaisajeBosque.png', name: 'Paisaje Bosque', category: 'CUSTOM' },
  { id: 's238', image: require('../../../assets/stickers/PaisajeDesierto.png'), fileName: 'PaisajeDesierto.png', name: 'Paisaje Desierto', category: 'CUSTOM' },
  { id: 's239', image: require('../../../assets/stickers/PaisajeMontanaSol.png'), fileName: 'PaisajeMontanaSol.png', name: 'Paisaje Montana Sol', category: 'CUSTOM' },
  { id: 's240', image: require('../../../assets/stickers/PaisajeVolcan.png'), fileName: 'PaisajeVolcan.png', name: 'Paisaje Volcan', category: 'CUSTOM' },
  { id: 's241', image: require('../../../assets/stickers/PerroVector.png'), fileName: 'PerroVector.png', name: 'Perro Vector', category: 'CUSTOM' },
  { id: 's242', image: require('../../../assets/stickers/SignoFemenino.png'), fileName: 'SignoFemenino.png', name: 'Signo Femenino', category: 'CUSTOM' },
  { id: 's243', image: require('../../../assets/stickers/Tauro.png'), fileName: 'Tauro.png', name: 'Tauro', category: 'CUSTOM' },
  { id: 's244', image: require('../../../assets/stickers/Virgo.png'), fileName: 'Virgo.png', name: 'Virgo', category: 'CUSTOM' },
  { id: 's245', image: require('../../../assets/stickers/Virgo2.png'), fileName: 'Virgo2.png', name: 'Virgo 2', category: 'CUSTOM' },
  { id: 's246', image: require('../../../assets/stickers/Zodiaco_Acuario.png'), fileName: 'Zodiaco_Acuario.png', name: 'Zodíaco Acuario', category: 'CUSTOM' },
  { id: 's247', image: require('../../../assets/stickers/Zodiaco_Aries.png'), fileName: 'Zodiaco_Aries.png', name: 'Zodíaco Aries', category: 'CUSTOM' },
  { id: 's248', image: require('../../../assets/stickers/Zodiaco_Cancer.png'), fileName: 'Zodiaco_Cancer.png', name: 'Zodíaco Cancer', category: 'CUSTOM' },
  { id: 's249', image: require('../../../assets/stickers/Zodiaco_Capricornio.png'), fileName: 'Zodiaco_Capricornio.png', name: 'Zodíaco Capricornio', category: 'CUSTOM' },
  { id: 's250', image: require('../../../assets/stickers/Zodiaco_Escorpio.png'), fileName: 'Zodiaco_Escorpio.png', name: 'Zodíaco Escorpio', category: 'CUSTOM' },
  { id: 's251', image: require('../../../assets/stickers/Zodiaco_Geminis.png'), fileName: 'Zodiaco_Geminis.png', name: 'Zodíaco Geminis', category: 'CUSTOM' },
  { id: 's252', image: require('../../../assets/stickers/Zodiaco_Leo.png'), fileName: 'Zodiaco_Leo.png', name: 'Zodíaco Leo', category: 'CUSTOM' },
  { id: 's253', image: require('../../../assets/stickers/Zodiaco_Libra.png'), fileName: 'Zodiaco_Libra.png', name: 'Zodíaco Libra', category: 'CUSTOM' },
  { id: 's254', image: require('../../../assets/stickers/Zodiaco_Piscis.png'), fileName: 'Zodiaco_Piscis.png', name: 'Zodíaco Piscis', category: 'CUSTOM' },
  { id: 's255', image: require('../../../assets/stickers/Zodiaco_Sagitario.png'), fileName: 'Zodiaco_Sagitario.png', name: 'Zodíaco Sagitario', category: 'CUSTOM' },
  { id: 's256', image: require('../../../assets/stickers/Zodiaco_Tauro.png'), fileName: 'Zodiaco_Tauro.png', name: 'Zodíaco Tauro', category: 'CUSTOM' },
  { id: 's257', image: require('../../../assets/stickers/Zodiaco_Virgo.png'), fileName: 'Zodiaco_Virgo.png', name: 'Zodíaco Virgo', category: 'CUSTOM' },
  { id: 's258', image: require('../../../assets/stickers/corazon.png'), fileName: 'corazon.png', name: 'Corazon', category: 'CUSTOM' },
  { id: 's259', image: require('../../../assets/stickers/flor1.png'), fileName: 'flor1.png', name: 'Flor 1', category: 'CUSTOM' },
  { id: 's260', image: require('../../../assets/stickers/flor2.png'), fileName: 'flor2.png', name: 'Flor 2', category: 'CUSTOM' },
  { id: 's261', image: require('../../../assets/stickers/flor3.png'), fileName: 'flor3.png', name: 'Flor 3', category: 'CUSTOM' },
  { id: 's262', image: require('../../../assets/stickers/flor4.png'), fileName: 'flor4.png', name: 'Flor 4', category: 'CUSTOM' },
  { id: 's263', image: require('../../../assets/stickers/gato10.png'), fileName: 'gato10.png', name: 'Gato 10', category: 'CUSTOM' },
  { id: 's264', image: require('../../../assets/stickers/gato11.png'), fileName: 'gato11.png', name: 'Gato 11', category: 'CUSTOM' },
  { id: 's265', image: require('../../../assets/stickers/gato13.png'), fileName: 'gato13.png', name: 'Gato 13', category: 'CUSTOM' },
  { id: 's266', image: require('../../../assets/stickers/gato2.png'), fileName: 'gato2.png', name: 'Gato 2', category: 'CUSTOM' },
  { id: 's267', image: require('../../../assets/stickers/gato3.png'), fileName: 'gato3.png', name: 'Gato 3', category: 'CUSTOM' },
  { id: 's268', image: require('../../../assets/stickers/gato4.png'), fileName: 'gato4.png', name: 'Gato 4', category: 'CUSTOM' },
  { id: 's269', image: require('../../../assets/stickers/gato5.png'), fileName: 'gato5.png', name: 'Gato 5', category: 'CUSTOM' },
  { id: 's270', image: require('../../../assets/stickers/gato6.png'), fileName: 'gato6.png', name: 'Gato 6', category: 'CUSTOM' },
  { id: 's271', image: require('../../../assets/stickers/gato7.png'), fileName: 'gato7.png', name: 'Gato 7', category: 'CUSTOM' },
  { id: 's272', image: require('../../../assets/stickers/gato8.png'), fileName: 'gato8.png', name: 'Gato 8', category: 'CUSTOM' },
  { id: 's273', image: require('../../../assets/stickers/gato9.png'), fileName: 'gato9.png', name: 'Gato 9', category: 'CUSTOM' },
  { id: 's274', image: require('../../../assets/stickers/mariposa3.png'), fileName: 'mariposa3.png', name: 'Mariposa 3', category: 'CUSTOM' },
  { id: 's275', image: require('../../../assets/stickers/mariposa5.png'), fileName: 'mariposa5.png', name: 'Mariposa 5', category: 'CUSTOM' },
  { id: 's276', image: require('../../../assets/stickers/oso1.png'), fileName: 'oso1.png', name: 'Oso 1', category: 'CUSTOM' },
  { id: 's277', image: require('../../../assets/stickers/oso2.png'), fileName: 'oso2.png', name: 'Oso 2', category: 'CUSTOM' },
  { id: 's278', image: require('../../../assets/stickers/oso3.png'), fileName: 'oso3.png', name: 'Oso 3', category: 'CUSTOM' },
  { id: 's279', image: require('../../../assets/stickers/oso4.png'), fileName: 'oso4.png', name: 'Oso 4', category: 'CUSTOM' },
  { id: 'e1', icon: '😀', name: 'Cara Sonriente', category: 'EMOJIS' },
  { id: 'e2', icon: '😃', name: 'Cara Abierta', category: 'EMOJIS' },
  { id: 'e3', icon: '😄', name: 'Cara Sonriente Feliz', category: 'EMOJIS' },
  { id: 'e4', icon: '😁', name: 'Cara Radiante', category: 'EMOJIS' },
  { id: 'e5', icon: '😆', name: 'Cara Riendo', category: 'EMOJIS' },
  { id: 'e6', icon: '😅', name: 'Risa Fria', category: 'EMOJIS' },
  { id: 'e7', icon: '😂', name: 'Risa con Llanto', category: 'EMOJIS' },
  { id: 'e8', icon: '🤣', name: 'Risa en el Suelo', category: 'EMOJIS' },
  { id: 'e9', icon: '😊', name: 'Cara Ojos Sonrientes', category: 'EMOJIS' },
  { id: 'e10', icon: '😇', name: 'Cara Angelical', category: 'EMOJIS' },
  { id: 'e11', icon: '🙂', name: 'Cara Leve Sonrisa', category: 'EMOJIS' },
  { id: 'e12', icon: '🙃', name: 'Cara al Reves', category: 'EMOJIS' },
  { id: 'e13', icon: '😉', name: 'Cara Guino', category: 'EMOJIS' },
  { id: 'e14', icon: '😌', name: 'Cara Aliviada', category: 'EMOJIS' },
  { id: 'e15', icon: '😍', name: 'Ojos de Corazon', category: 'EMOJIS' },
  { id: 'e16', icon: '🥰', name: 'Cara con Corazones', category: 'EMOJIS' },
  { id: 'e17', icon: '😘', name: 'Beso de Corazon', category: 'EMOJIS' },
  { id: 'e18', icon: '😗', name: 'Beso', category: 'EMOJIS' },
  { id: 'e19', icon: '😙', name: 'Beso Ojos Sonrientes', category: 'EMOJIS' },
  { id: 'e20', icon: '😚', name: 'Beso Cerrado', category: 'EMOJIS' },
  { id: 'e21', icon: '😋', name: 'Cara Saboreando', category: 'EMOJIS' },
  { id: 'e22', icon: '😛', name: 'Cara Sacando Lengua', category: 'EMOJIS' },
  { id: 'e23', icon: '😝', name: 'Guino y Lengua', category: 'EMOJIS' },
  { id: 'e24', icon: '😜', name: 'Guino Ojo y Lengua', category: 'EMOJIS' },
  { id: 'e25', icon: '🤪', name: 'Cara Loca', category: 'EMOJIS' },
  { id: 'e26', icon: '🤨', name: 'Ceja Levantada', category: 'EMOJIS' },
  { id: 'e27', icon: '🧐', name: 'Monoculo', category: 'EMOJIS' },
  { id: 'e28', icon: '🤓', name: 'Cara Nerd', category: 'EMOJIS' },
  { id: 'e29', icon: '😎', name: 'Cara con Anteojos', category: 'EMOJIS' },
  { id: 'e30', icon: '🥸', name: 'Disfraz', category: 'EMOJIS' },
  { id: 'e31', icon: '🤩', name: 'Ojos de Estrella', category: 'EMOJIS' },
  { id: 'e32', icon: '🥳', name: 'Cara de Fiesta', category: 'EMOJIS' },
  { id: 'e33', icon: '😏', name: 'Cara Picardia', category: 'EMOJIS' },
  { id: 'e34', icon: '😒', name: 'Cara Descontento', category: 'EMOJIS' },
  { id: 'e35', icon: '😞', name: 'Cara Decepcionada', category: 'EMOJIS' },
  { id: 'e36', icon: '😔', name: 'Pensativo', category: 'EMOJIS' },
  { id: 'e37', icon: '😟', name: 'Preocupado', category: 'EMOJIS' },
  { id: 'e38', icon: '😕', name: 'Confundido', category: 'EMOJIS' },
  { id: 'e39', icon: '🙁', name: 'Leve Triste', category: 'EMOJIS' },
  { id: 'e40', icon: '☹️', name: 'Triste', category: 'EMOJIS' },
  { id: 'e41', icon: '😣', name: 'Perseverante', category: 'EMOJIS' },
  { id: 'e42', icon: '😖', name: 'Confundido Fuerte', category: 'EMOJIS' },
  { id: 'e43', icon: '😫', name: 'Cansado', category: 'EMOJIS' },
  { id: 'e44', icon: '😩', name: 'Fatigado', category: 'EMOJIS' },
  { id: 'e45', icon: '🥺', name: 'Ojos Rogantes', category: 'EMOJIS' },
  { id: 'e46', icon: '😢', name: 'Cara con Lagrima', category: 'EMOJIS' },
  { id: 'e47', icon: '😭', name: 'Llanto Fuerte', category: 'EMOJIS' },
  { id: 'e48', icon: '😤', name: 'Triunfo Humo', category: 'EMOJIS' },
  { id: 'e49', icon: '😠', name: 'Enojado', category: 'EMOJIS' },
  { id: 'e50', icon: '😡', name: 'Muy Enojado', category: 'EMOJIS' },
  { id: 'e51', icon: '🤬', name: 'Insultos', category: 'EMOJIS' },
  { id: 'e52', icon: '🤯', name: 'Cabeza Explotada', category: 'EMOJIS' },
  { id: 'e53', icon: '😳', name: 'Sonrojado', category: 'EMOJIS' },
  { id: 'e54', icon: '🥵', name: 'Calor', category: 'EMOJIS' },
  { id: 'e55', icon: '🥶', name: 'Frio', category: 'EMOJIS' },
  { id: 'e56', icon: '😱', name: 'Grito de Terror', category: 'EMOJIS' },
  { id: 'e57', icon: '😨', name: 'Temeroso', category: 'EMOJIS' },
  { id: 'e58', icon: '😰', name: 'Sudor Frio', category: 'EMOJIS' },
  { id: 'e59', icon: '😥', name: 'Triste Aliviado', category: 'EMOJIS' },
  { id: 'e60', icon: '🤤', name: 'Cara Babeante', category: 'EMOJIS' },
  { id: 'e61', icon: '🤢', name: 'Asco', category: 'EMOJIS' },
  { id: 'e62', icon: '🤮', name: 'Vomito', category: 'EMOJIS' },
  { id: 'e63', icon: '🤧', name: 'Estornudo', category: 'EMOJIS' },
  { id: 'e64', icon: '😷', name: 'Mascarilla', category: 'EMOJIS' },
  { id: 'e65', icon: '🤒', name: 'Termometro', category: 'EMOJIS' },
  { id: 'e66', icon: '🤕', name: 'Venda', category: 'EMOJIS' },
  { id: 'e67', icon: '💀', name: 'Calavera', category: 'EMOJIS' },
  { id: 'e68', icon: '☠️', name: 'Calavera Pirata', category: 'EMOJIS' },
  { id: 'e69', icon: '👻', name: 'Fantasma', category: 'EMOJIS' },
  { id: 'e70', icon: '👽', name: 'Alien', category: 'EMOJIS' },
  { id: 'e71', icon: '👾', name: 'Monstruo de Pixel', category: 'EMOJIS' },
  { id: 'e72', icon: '🤖', name: 'Robot', category: 'EMOJIS' },
  { id: 'e73', icon: '💩', name: 'Caca con Ojos', category: 'EMOJIS' },
  { id: 'e74', icon: '🎃', name: 'Calabaza Halloween', category: 'EMOJIS' },
  { id: 'e75', icon: '👋', name: 'Saludo Mano', category: 'EMOJIS' },
  { id: 'e76', icon: '🤚', name: 'Dorso Mano', category: 'EMOJIS' },
  { id: 'e77', icon: '🖐️', name: 'Mano Abierta', category: 'EMOJIS' },
  { id: 'e78', icon: '✋', name: 'Mano Levantada', category: 'EMOJIS' },
  { id: 'e79', icon: '🖖', name: 'Saludo Vulcano', category: 'EMOJIS' },
  { id: 'e80', icon: '👌', name: 'Mano OK', category: 'EMOJIS' },
  { id: 'e81', icon: '🤌', name: 'Mano Italiana', category: 'EMOJIS' },
  { id: 'e82', icon: '🤏', name: 'Poco', category: 'EMOJIS' },
  { id: 'e83', icon: '✌️', name: 'Paz y Amor', category: 'EMOJIS' },
  { id: 'e84', icon: '🤞', name: 'Dedos Cruzados', category: 'EMOJIS' },
  { id: 'e85', icon: '🤟', name: 'Te Amo Mano', category: 'EMOJIS' },
  { id: 'e86', icon: '🤘', name: 'Rock On', category: 'EMOJIS' },
  { id: 'e87', icon: '🤙', name: 'Llamame', category: 'EMOJIS' },
  { id: 'e88', icon: '👈', name: 'Apunta Izquierda', category: 'EMOJIS' },
  { id: 'e89', icon: '👉', name: 'Apunta Derecha', category: 'EMOJIS' },
  { id: 'e90', icon: '👆', name: 'Apunta Arriba', category: 'EMOJIS' },
  { id: 'e91', icon: '🖕', name: 'Dedo Medio', category: 'EMOJIS' },
  { id: 'e92', icon: '👇', name: 'Apunta Abajo', category: 'EMOJIS' },
  { id: 'e93', icon: '☝️', name: 'Indice Arriba', category: 'EMOJIS' },
  { id: 'e94', icon: '👍', name: 'Pulgar Arriba', category: 'EMOJIS' },
  { id: 'e95', icon: '👎', name: 'Pulgar Abajo', category: 'EMOJIS' },
  { id: 'e96', icon: '✊', name: 'Puno', category: 'EMOJIS' },
  { id: 'e97', icon: '👊', name: 'Puno Frente', category: 'EMOJIS' },
  { id: 'e98', icon: '🤛', name: 'Puno Izquierda', category: 'EMOJIS' },
  { id: 'e99', icon: '🤜', name: 'Puno Derecha', category: 'EMOJIS' },
  { id: 'e100', icon: '👏', name: 'Aplauso', category: 'EMOJIS' },
  { id: 'e101', icon: '🙌', name: 'Manos Arriba', category: 'EMOJIS' },
  { id: 'e102', icon: '👐', name: 'Manos Abiertas', category: 'EMOJIS' },
  { id: 'e103', icon: '🤲', name: 'Palmas Juntas', category: 'EMOJIS' },
  { id: 'e104', icon: '🤝', name: 'Apreton Manos', category: 'EMOJIS' },
  { id: 'e105', icon: '🙏', name: 'Favor / Rezo', category: 'EMOJIS' },
  { id: 'e106', icon: '✍️', name: 'Escribir', category: 'EMOJIS' },
  { id: 'e107', icon: '💅', name: 'Esmalte Unas', category: 'EMOJIS' },
  { id: 'e108', icon: '🤳', name: 'Selfie', category: 'EMOJIS' },
  { id: 'e109', icon: '💪', name: 'Fuerza Bicep', category: 'EMOJIS' },
  { id: 'e110', icon: '❤️', name: 'Corazon Rojo', category: 'EMOJIS' },
  { id: 'e111', icon: '🧡', name: 'Corazon Naranja', category: 'EMOJIS' },
  { id: 'e112', icon: '💛', name: 'Corazon Amarillo', category: 'EMOJIS' },
  { id: 'e113', icon: '💚', name: 'Corazon Verde', category: 'EMOJIS' },
  { id: 'e114', icon: '💙', name: 'Corazon Azul', category: 'EMOJIS' },
  { id: 'e115', icon: '💜', name: 'Corazon Violeta', category: 'EMOJIS' },
  { id: 'e116', icon: '🖤', name: 'Corazon Negro', category: 'EMOJIS' },
  { id: 'e117', icon: '🤍', name: 'Corazon Blanco', category: 'EMOJIS' },
  { id: 'e118', icon: '🤎', name: 'Corazon Marron', category: 'EMOJIS' },
  { id: 'e119', icon: '💔', name: 'Corazon Roto', category: 'EMOJIS' },
  { id: 'e120', icon: '❤️‍🔥', name: 'Corazon en Fuego', category: 'EMOJIS' },
  { id: 'e121', icon: '❤️‍🩹', name: 'Corazon Vendado', category: 'EMOJIS' },
  { id: 'e122', icon: '❣', name: 'Exclamacion Corazon', category: 'EMOJIS' },
  { id: 'e123', icon: '💕', name: 'Dos Corazones', category: 'EMOJIS' },
  { id: 'e124', icon: '💞', name: 'Corazones Giratorios', category: 'EMOJIS' },
  { id: 'e125', icon: '🐶', name: 'Perro', category: 'EMOJIS' },
  { id: 'e126', icon: '🐱', name: 'Gato', category: 'EMOJIS' },
  { id: 'e127', icon: '🐭', name: 'Raton', category: 'EMOJIS' },
  { id: 'e128', icon: '🐹', name: 'Hamster', category: 'EMOJIS' },
  { id: 'e129', icon: '🐰', name: 'Conejo', category: 'EMOJIS' },
  { id: 'e130', icon: '🦊', name: 'Zorro', category: 'EMOJIS' },
  { id: 'e131', icon: '🐻', name: 'Oso', category: 'EMOJIS' },
  { id: 'e132', icon: '🐼', name: 'Panda', category: 'EMOJIS' },
  { id: 'e133', icon: '🐨', name: 'Koala', category: 'EMOJIS' },
  { id: 'e134', icon: '🐯', name: 'Tigre', category: 'EMOJIS' },
  { id: 'e135', icon: '🦁', name: 'Leon', category: 'EMOJIS' },
  { id: 'e136', icon: '🐮', name: 'Vaca', category: 'EMOJIS' },
  { id: 'e137', icon: '🐷', name: 'Chancho', category: 'EMOJIS' },
  { id: 'e138', icon: '🐸', name: 'Sapo', category: 'EMOJIS' },
  { id: 'e139', icon: '🐒', name: 'Mono', category: 'EMOJIS' },
  { id: 'e140', icon: '🐔', name: 'Gallina', category: 'EMOJIS' },
  { id: 'e141', icon: '🐧', name: 'Pinguino', category: 'EMOJIS' },
  { id: 'e142', icon: '🐦', name: 'Pajaro', category: 'EMOJIS' },
  { id: 'e143', icon: '🐤', name: 'Pollito', category: 'EMOJIS' },
  { id: 'e144', icon: '🦆', name: 'Pato', category: 'EMOJIS' },
  { id: 'e145', icon: '🦅', name: 'Aguila', category: 'EMOJIS' },
  { id: 'e146', icon: '🦉', name: 'Buho', category: 'EMOJIS' },
  { id: 'e147', icon: '🦇', name: 'Murcielago', category: 'EMOJIS' },
  { id: 'e148', icon: '🐺', name: 'Lobo', category: 'EMOJIS' },
  { id: 'e149', icon: '🐗', name: 'Jabali', category: 'EMOJIS' },
  { id: 'e150', icon: '🐴', name: 'Caballo', category: 'EMOJIS' },
  { id: 'e151', icon: '🦄', name: 'Unicornio', category: 'EMOJIS' },
  { id: 'e152', icon: '🐝', name: 'Abeja', category: 'EMOJIS' },
  { id: 'e153', icon: '🐛', name: 'Oruga', category: 'EMOJIS' },
  { id: 'e154', icon: '🦋', name: 'Mariposa', category: 'EMOJIS' },
  { id: 'e155', icon: '🐌', name: 'Caracol', category: 'EMOJIS' },
  { id: 'e156', icon: '🐞', name: 'Vaquita de San Antonio', category: 'EMOJIS' },
  { id: 'e157', icon: 'Ant', name: 'Hormiga', category: 'EMOJIS' },
  { id: 'e158', icon: 'Mosquito', name: 'Mosquito', category: 'EMOJIS' },
  { id: 'e159', icon: 'Cricket', name: 'Grillo', category: 'EMOJIS' },
  { id: 'e160', icon: '🕷️', name: 'Arana', category: 'EMOJIS' },
  { id: 'e161', icon: '🦂', name: 'Escorpion', category: 'EMOJIS' },
  { id: 'e162', icon: '🐢', name: 'Tortuga', category: 'EMOJIS' },
  { id: 'e163', icon: '🐍', name: 'Serpiente', category: 'EMOJIS' },
  { id: 'e164', icon: '🦎', name: 'Lagartija', category: 'EMOJIS' },
  { id: 'e165', icon: '🐙', name: 'Pulpo', category: 'EMOJIS' },
  { id: 'e166', icon: '🦑', name: 'Calamar', category: 'EMOJIS' },
  { id: 'e167', icon: '🦞', name: 'Langosta', category: 'EMOJIS' },
  { id: 'e168', icon: '🦀', name: 'Cangrejo', category: 'EMOJIS' },
  { id: 'e169', icon: '🐡', name: 'Pez Globo', category: 'EMOJIS' },
  { id: 'e170', icon: '🐠', name: 'Pez Tropical', category: 'EMOJIS' },
  { id: 'e171', icon: '🐟', name: 'Pez', category: 'EMOJIS' },
  { id: 'e172', icon: '🐬', name: 'Delfin', category: 'EMOJIS' },
  { id: 'e173', icon: '🐳', name: 'Ballena', category: 'EMOJIS' },
  { id: 'e174', icon: '🦈', name: 'Tiburon', category: 'EMOJIS' },
  { id: 'e175', icon: '🐊', name: 'Cocodrilo', category: 'EMOJIS' },
  { id: 'e176', icon: '🦖', name: 'Dinosaurio T-Rex', category: 'EMOJIS' },
  { id: 'e177', icon: '🦕', name: 'Dinosaurio Cuello Largo', category: 'EMOJIS' },
  { id: 'e178', icon: '💐', name: 'Ramo Flores', category: 'EMOJIS' },
  { id: 'e179', icon: '🌸', name: 'Flor Cerezo', category: 'EMOJIS' },
  { id: 'e180', icon: '💮', name: 'Flor Blanca', category: 'EMOJIS' },
  { id: 'e181', icon: '🏵️', name: 'Roseta', category: 'EMOJIS' },
  { id: 'e182', icon: '🌹', name: 'Rosa', category: 'EMOJIS' },
  { id: 'e183', icon: '🥀', name: 'Flor Marchita', category: 'EMOJIS' },
  { id: 'e184', icon: '🌺', name: 'Hibisco', category: 'EMOJIS' },
  { id: 'e185', icon: '🌻', name: 'Girasol', category: 'EMOJIS' },
  { id: 'e186', icon: '🌼', name: 'Flor Amarilla', category: 'EMOJIS' },
  { id: 'e187', icon: '🌷', name: 'Tulipan', category: 'EMOJIS' },
  { id: 'e188', icon: '🌱', name: 'Brote', category: 'EMOJIS' },
  { id: 'e189', icon: '🌲', name: 'Pino', category: 'EMOJIS' },
  { id: 'e190', icon: '🌳', name: 'Arbol', category: 'EMOJIS' },
  { id: 'e191', icon: '🌴', name: 'Palmera', category: 'EMOJIS' },
  { id: 'e192', icon: '🌵', name: 'Cactus', category: 'EMOJIS' },
  { id: 'e193', icon: '🌾', name: 'Espiga', category: 'EMOJIS' },
  { id: 'e194', icon: '🌿', name: 'Hierba', category: 'EMOJIS' },
  { id: 'e195', icon: '🍀', name: 'Trebol', category: 'EMOJIS' },
  { id: 'e196', icon: '🍁', name: 'Hoja Otono', category: 'EMOJIS' },
  { id: 'e197', icon: '🍂', name: 'Hoja Seca', category: 'EMOJIS' },
  { id: 'e198', icon: '🍃', name: 'Hoja Viento', category: 'EMOJIS' },
  { id: 'e199', icon: '🧉', name: 'Mate', category: 'EMOJIS' },
  { id: 'e200', icon: '🍕', name: 'Pizza', category: 'EMOJIS' },
  { id: 'e201', icon: '🍔', name: 'Hamburguesa', category: 'EMOJIS' },
  { id: 'e202', icon: '🍟', name: 'Papas Fritas', category: 'EMOJIS' },
  { id: 'e203', icon: '🌭', name: 'Pancho', category: 'EMOJIS' },
  { id: 'e204', icon: '🍿', name: 'Pococrlo', category: 'EMOJIS' },
  { id: 'e205', icon: '🌮', name: 'Taco', category: 'EMOJIS' },
  { id: 'e206', icon: '🌯', name: 'Burrito', category: 'EMOJIS' },
  { id: 'e207', icon: '🍳', name: 'Huevo Frito', category: 'EMOJIS' },
  { id: 'e208', icon: '🥞', name: 'Panqueques', category: 'EMOJIS' },
  { id: 'e209', icon: '🥓', name: 'Panceta', category: 'EMOJIS' },
  { id: 'e210', icon: '🥩', name: 'Carne', category: 'EMOJIS' },
  { id: 'e211', icon: '🍗', name: 'Pata Pollo', category: 'EMOJIS' },
  { id: 'e212', icon: '🍖', name: 'Hueso Carne', category: 'EMOJIS' },
  { id: 'e213', icon: '🧀', name: 'Queso', category: 'EMOJIS' },
  { id: 'e214', icon: '🍞', name: 'Pan', category: 'EMOJIS' },
  { id: 'e215', icon: '🥐', name: 'Medialuna', category: 'EMOJIS' },
  { id: 'e216', icon: '🥨', name: 'Pretzel', category: 'EMOJIS' },
  { id: 'e217', icon: '🍩', name: 'Dona', category: 'EMOJIS' },
  { id: 'e218', icon: '🍪', name: 'Galletita', category: 'EMOJIS' },
  { id: 'e219', icon: '🎂', name: 'Torta Cumpleanos', category: 'EMOJIS' },
  { id: 'e220', icon: '🍰', name: 'Porcion Torta', category: 'EMOJIS' },
  { id: 'e221', icon: '🧁', name: 'Cupcake', category: 'EMOJIS' },
  { id: 'e222', icon: '🥧', name: 'Tarta', category: 'EMOJIS' },
  { id: 'e223', icon: '🍫', name: 'Chocolate', category: 'EMOJIS' },
  { id: 'e224', icon: '🍬', name: 'Caramelo', category: 'EMOJIS' },
  { id: 'e225', icon: '🍭', name: 'Chupetin', category: 'EMOJIS' },
  { id: 'e226', icon: '🍮', name: 'Flan', category: 'EMOJIS' },
  { id: 'e227', icon: '🍯', name: 'Pote de Miel', category: 'EMOJIS' },
  { id: 'e228', icon: '🍎', name: 'Manzana Roja', category: 'EMOJIS' },
  { id: 'e229', icon: '🍏', name: 'Manzana Verde', category: 'EMOJIS' },
  { id: 'e230', icon: '🍐', name: 'Pera', category: 'EMOJIS' },
  { id: 'e231', icon: '🍑', name: 'Durazno', category: 'EMOJIS' },
  { id: 'e232', icon: '🍒', name: 'Cerezas', category: 'EMOJIS' },
  { id: 'e233', icon: '🍓', name: 'Frutilla', category: 'EMOJIS' },
  { id: 'e234', icon: '🍌', name: 'Banana', category: 'EMOJIS' },
  { id: 'e235', icon: '🍉', name: 'Sandia', category: 'EMOJIS' },
  { id: 'e236', icon: '🍇', name: 'Uva', category: 'EMOJIS' },
  { id: 'e237', icon: '🍈', name: 'Melon', category: 'EMOJIS' },
  { id: 'e238', icon: '🍊', name: 'Naranja', category: 'EMOJIS' },
  { id: 'e239', icon: '🍋', name: 'Limon', category: 'EMOJIS' },
  { id: 'e240', icon: '🍍', name: 'Pina', category: 'EMOJIS' },
  { id: 'e241', icon: '🥥', name: 'Coco', category: 'EMOJIS' },
  { id: 'e242', icon: '🥝', name: 'Kiwi', category: 'EMOJIS' },
  { id: 'e243', icon: '🍅', name: 'Tomate', category: 'EMOJIS' },
  { id: 'e244', icon: '🥑', name: 'Palta', category: 'EMOJIS' },
  { id: 'e245', icon: '🍆', name: 'Berenjena', category: 'EMOJIS' },
  { id: 'e246', icon: '🥔', name: 'Papa', category: 'EMOJIS' },
  { id: 'e247', icon: '🥕', name: 'Zanahoria', category: 'EMOJIS' },
  { id: 'e248', icon: '🌽', name: 'Choclo', category: 'EMOJIS' },
  { id: 'e249', icon: '🌶️', name: 'Aji Picante', category: 'EMOJIS' },
  { id: 'e250', icon: '🥒', name: 'Pepino', category: 'EMOJIS' },
  { id: 'e251', icon: '🥬', name: 'Lechuga', category: 'EMOJIS' },
  { id: 'e252', icon: '🥦', name: 'Brocoli', category: 'EMOJIS' },
  { id: 'e253', icon: '🍄', name: 'Hongo', category: 'EMOJIS' },
  { id: 'e254', icon: '🥜', name: 'Mani', category: 'EMOJIS' },
  { id: 'e255', icon: '🍚', name: 'Arroz', category: 'EMOJIS' },
  { id: 'e256', icon: '🍜', name: 'Fideos Ramen', category: 'EMOJIS' },
  { id: 'e257', icon: '🍣', name: 'Sushi', category: 'EMOJIS' },
  { id: 'e258', icon: '🍤', name: 'Camaron Frito', category: 'EMOJIS' },
  { id: 'e259', icon: '🥟', name: 'Empanada China', category: 'EMOJIS' },
  { id: 'e260', icon: '🍨', name: 'Helado Copa', category: 'EMOJIS' },
  { id: 'e261', icon: '🍦', name: 'Helado Cono', category: 'EMOJIS' },
  { id: 'e262', icon: '☕', name: 'Cafe', category: 'EMOJIS' },
  { id: 'e263', icon: '🍵', name: 'Te', category: 'EMOJIS' },
  { id: 'e264', icon: '🍶', name: 'Sake', category: 'EMOJIS' },
  { id: 'e265', icon: '🍾', name: 'Champana', category: 'EMOJIS' },
  { id: 'e266', icon: '🍷', name: 'Vino', category: 'EMOJIS' },
  { id: 'e267', icon: '🍸', name: 'Trago', category: 'EMOJIS' },
  { id: 'e268', icon: '🍹', name: 'Trago Tropical', category: 'EMOJIS' },
  { id: 'e269', icon: '🍺', name: 'Cerveza Chopp', category: 'EMOJIS' },
  { id: 'e270', icon: '🍻', name: 'Brindis Cerveza', category: 'EMOJIS' },
  { id: 'e271', icon: '🥤', name: 'Gaseosa', category: 'EMOJIS' },
  { id: 'e272', icon: '🧃', name: 'Juguito', category: 'EMOJIS' },
  { id: 'e273', icon: '🥛', name: 'Vaso Leche', category: 'EMOJIS' },
  { id: 'e274', icon: '🧊', name: 'Hielo', category: 'EMOJIS' },
  { id: 'e275', icon: '🚗', name: 'Auto Rojo', category: 'EMOJIS' },
  { id: 'e276', icon: '🚕', name: 'Taxi', category: 'EMOJIS' },
  { id: 'e277', icon: '🚙', name: 'Auto Azul', category: 'EMOJIS' },
  { id: 'e278', icon: '🚌', name: 'Colectivo', category: 'EMOJIS' },
  { id: 'e279', icon: '🏎️', name: 'Formula 1', category: 'EMOJIS' },
  { id: 'e280', icon: '🚓', name: 'Patrullero', category: 'EMOJIS' },
  { id: 'e281', icon: '🚑', name: 'Ambulancia', category: 'EMOJIS' },
  { id: 'e282', icon: '🚒', name: 'Bomberos', category: 'EMOJIS' },
  { id: 'e283', icon: '🚚', name: 'Camion de Reparto', category: 'EMOJIS' },
  { id: 'e284', icon: '🚜', name: 'Tractor', category: 'EMOJIS' },
  { id: 'e285', icon: '🏍️', name: 'Moto', category: 'EMOJIS' },
  { id: 'e286', icon: '🚲', name: 'Bicicleta', category: 'EMOJIS' },
  { id: 'e287', icon: 'Monopatin', name: 'Monopatin', category: 'EMOJIS' },
  { id: 'e288', icon: '🛹', name: 'Skate Board', category: 'EMOJIS' },
  { id: 'e289', icon: '🚆', name: 'Tren Bala', category: 'EMOJIS' },
  { id: 'e290', icon: '🚁', name: 'Helicoptero', category: 'EMOJIS' },
  { id: 'e291', icon: '✈️', name: 'Avion Comercial', category: 'EMOJIS' },
  { id: 'e292', icon: '🪂', name: 'Paracaidas', category: 'EMOJIS' },
  { id: 'e293', icon: '🚀', name: 'Cohete', category: 'EMOJIS' },
  { id: 'e294', icon: '🛸', name: 'Plato Volador', category: 'EMOJIS' },
  { id: 'e295', icon: '⛵', name: 'Velero', category: 'EMOJIS' },
  { id: 'e296', icon: '🛥️', name: 'Lancha Motora', category: 'EMOJIS' },
  { id: 'e297', icon: '🚢', name: 'Barco Crucero', category: 'EMOJIS' },
  { id: 'e298', icon: '⚓', name: 'Ancla Marina', category: 'EMOJIS' },
  { id: 'e299', icon: '⚽', name: 'Pelota Futbol', category: 'EMOJIS' },
  { id: 'e300', icon: '🏀', name: 'Pelota Basquet', category: 'EMOJIS' },
  { id: 'e301', icon: '🏈', name: 'Pelota Rugby', category: 'EMOJIS' },
  { id: 'e302', icon: '⚾', name: 'Pelota Beisbol', category: 'EMOJIS' },
  { id: 'e303', icon: '🥎', name: 'Pelota Softbol', category: 'EMOJIS' },
  { id: 'e304', icon: '🎾', name: 'Pelota Tenis', category: 'EMOJIS' },
  { id: 'e305', icon: ' volleyball', name: 'Pelota Voley', category: 'EMOJIS' },
  { id: 'e306', icon: '🎱', name: 'Bola 8 Billar', category: 'EMOJIS' },
  { id: 'e307', icon: '🧿', name: 'Ojo Turco', category: 'EMOJIS' },
  { id: 'e308', icon: '🎮', name: 'Joystick', category: 'EMOJIS' },
  { id: 'e309', icon: '🕹️', name: 'Palanca Retro', category: 'EMOJIS' },
  { id: 'e310', icon: '👾', name: 'Pixel Alien', category: 'EMOJIS' },
  { id: 'e311', icon: '🎯', name: 'Blanco y Dardo', category: 'EMOJIS' },
  { id: 'e312', icon: '🏆', name: 'Copa Oro', category: 'EMOJIS' },
  { id: 'e313', icon: '🥇', name: 'Medalla Oro', category: 'EMOJIS' },
  { id: 'e314', icon: '🥈', name: 'Medalla Plata', category: 'EMOJIS' },
  { id: 'e315', icon: '🥉', name: 'Medalla Bronce', category: 'EMOJIS' },
  { id: 'e316', icon: '🎟️', name: 'Entradas', category: 'EMOJIS' },
  { id: 'e317', icon: '🎪', name: 'Carpa Circo', category: 'EMOJIS' },
  { id: 'e318', icon: '🎨', name: 'Paleta Pintor', category: 'EMOJIS' },
  { id: 'e319', icon: '🎬', name: 'Claqueta Cine', category: 'EMOJIS' },
  { id: 'e320', icon: '🎤', name: 'Microfono', category: 'EMOJIS' },
  { id: 'e321', icon: '🎧', name: 'Auriculares', category: 'EMOJIS' },
  { id: 'e322', icon: '🎸', name: 'Guitarra Electrica', category: 'EMOJIS' },
  { id: 'e323', icon: '🎻', name: 'Violin', category: 'EMOJIS' },
  { id: 'e324', icon: '📱', name: 'Celular', category: 'EMOJIS' },
  { id: 'e325', icon: '☎️', name: 'Telefono Fijo', category: 'EMOJIS' },
  { id: 'e326', icon: '🔋', name: 'Bateria', category: 'EMOJIS' },
  { id: 'e327', icon: '🔌', name: 'Enchufe', category: 'EMOJIS' },
  { id: 'e328', icon: '💻', name: 'Notebook', category: 'EMOJIS' },
  { id: 'e329', icon: '📺', name: 'Televisor', category: 'EMOJIS' },
  { id: 'e330', icon: '📷', name: 'Camara Fotos', category: 'EMOJIS' },
  { id: 'e331', icon: '🔍', name: 'Lupa', category: 'EMOJIS' },
  { id: 'e332', icon: '💡', name: 'Lamparita', category: 'EMOJIS' },
  { id: 'e333', icon: 'Linterna', name: 'Linterna', category: 'EMOJIS' },
  { id: 'e334', icon: '📔', name: 'Agenda', category: 'EMOJIS' },
  { id: 'e335', icon: '📕', name: 'Libro Rojo', category: 'EMOJIS' },
  { id: 'e336', icon: '📖', name: 'Libro Abierto', category: 'EMOJIS' },
  { id: 'e337', icon: '📚', name: 'Pila Libros', category: 'EMOJIS' },
  { id: 'e338', icon: '✉️', name: 'Sobre Carta', category: 'EMOJIS' },
  { id: 'e339', icon: '📦', name: 'Caja Envio', category: 'EMOJIS' },
  { id: 'e340', icon: '✏️', name: 'Lapiz', category: 'EMOJIS' },
  { id: 'e341', icon: '✒️', name: 'Pluma Estilografica', category: 'EMOJIS' },
  { id: 'e342', icon: '📎', name: 'Clip', category: 'EMOJIS' },
  { id: 'e343', icon: '📐', name: 'Escuadra', category: 'EMOJIS' },
  { id: 'e344', icon: '🔨', name: 'Martillo', category: 'EMOJIS' },
  { id: 'e345', icon: '🔧', name: 'Llave Inglesa', category: 'EMOJIS' },
  { id: 'e346', icon: '⚙️', name: 'Engranaje', category: 'EMOJIS' },
  { id: 'e347', icon: '🧱', name: 'Ladrillo', category: 'EMOJIS' },
  { id: 'e348', icon: '⚖️', name: 'Balanza de la Justicia', category: 'EMOJIS' },
  { id: 'e349', icon: '⛓️', name: 'Cadena', category: 'EMOJIS' },
  { id: 'e350', icon: '🔑', name: 'Llave Metal', category: 'EMOJIS' },
  { id: 'e351', icon: '🔒', name: 'Candado Cerrado', category: 'EMOJIS' },
  { id: 'e352', icon: '🔓', name: 'Candado Abierto', category: 'EMOJIS' },
  { id: 'e353', icon: '🛡️', name: 'Escudo Protector', category: 'EMOJIS' },
  { id: 'e354', icon: '🏹', name: 'Arco y Flecha', category: 'EMOJIS' },
  { id: 'e355', icon: '🗡️', name: 'Daga', category: 'EMOJIS' },
  { id: 'e356', icon: '⚔️', name: 'Espadas Cruzadas', category: 'EMOJIS' },
  { id: 'e357', icon: '💣', name: 'Bomba', category: 'EMOJIS' },
  { id: 'e358', icon: '🔥', name: 'Fuego', category: 'EMOJIS' },
  { id: 'e359', icon: '⭐', name: 'Estrella Dorada', category: 'EMOJIS' },
  { id: 'e360', icon: '✨', name: 'Destellos', category: 'EMOJIS' },
  { id: 'e361', icon: '🌟', name: 'Estrella Variante', category: 'EMOJIS' },
  { id: 'e362', icon: '⚡', name: 'Rayo Electrico', category: 'EMOJIS' },
  { id: 'e363', icon: '☄️', name: 'Cometa', category: 'EMOJIS' },
  { id: 'e364', icon: '🌈', name: 'Arcoiris', category: 'EMOJIS' },
  { id: 'e365', icon: '☀️', name: 'Sol Radiante', category: 'EMOJIS' },
  { id: 'e366', icon: '🌤️', name: 'Sol entre Nubes', category: 'EMOJIS' },
  { id: 'e367', icon: '⛅', name: 'Nube con Sol', category: 'EMOJIS' },
  { id: 'e368', icon: '🌧️', name: 'Nube Lluvia', category: 'EMOJIS' },
  { id: 'e369', icon: '⛈️', name: 'Nube Tormenta', category: 'EMOJIS' },
  { id: 'e370', icon: '❄️', name: 'Copo Nieve', category: 'EMOJIS' },
  { id: 'e371', icon: '🌬️', name: 'Viento Soplador', category: 'EMOJIS' },
  { id: 'e372', icon: '🌊', name: 'Ola de Mar', category: 'EMOJIS' },
  { id: 'e373', icon: '💧', name: 'Gota de Agua', category: 'EMOJIS' },
  { id: 'e374', icon: '🎈', name: 'Globo Fiesta', category: 'EMOJIS' },
  { id: 'e375', icon: '🎉', name: 'Festejo', category: 'EMOJIS' },
  { id: 'e376', icon: '🚩', name: 'Bandera Roja', category: 'EMOJIS' },
  { id: 'e377', icon: '🏁', name: 'Bandera Cuadros', category: 'EMOJIS' },
  { id: 'e378', icon: '💯', name: 'Cien Puntos', category: 'EMOJIS' },
  { id: 'e379', icon: '🔞', name: 'Mas de 18 Anos', category: 'EMOJIS' },

  // GYM
  { id: 'gym1', icon: '🏃', name: 'Cinta de Correr', category: 'GYM' },
  { id: 'gym2', icon: '🚴', name: 'Bicicleta Fija', category: 'GYM' },
  { id: 'gym3', icon: '🚣', name: 'Máquina de Remo', category: 'GYM' },
  { id: 'gym4', icon: '🧗', name: 'Escaladora (Cardio)', category: 'GYM' },
  { id: 'gym5', icon: '🧘', name: 'Estiramiento', category: 'GYM' },
  { id: 'gym6', icon: '🧎', name: 'Zancadas (Lunge)', category: 'GYM' },
  { id: 'gym7', icon: '🚶', name: 'Caminata', category: 'GYM' },
  { id: 'gym8', icon: '🥊', name: 'Bolsa de Boxeo', category: 'GYM' },
  { id: 'gym9', icon: '🥤', name: 'Hidratación / Shaker', category: 'GYM' },
  { id: 'gym10', icon: '🧖', name: 'Sauna / Recuperación', category: 'GYM' },

  // DEPORTES
  { id: 'dep1', icon: '⚽', name: 'Fútbol', category: 'DEPORTES' },
  { id: 'dep2', icon: '🏀', name: 'Básquetbol', category: 'DEPORTES' },
  { id: 'dep3', icon: '🎾', name: 'Tenis', category: 'DEPORTES' },
  { id: 'dep4', icon: '🏐', name: 'Vóleibol', category: 'DEPORTES' },
  { id: 'dep5', icon: '🏈', name: 'Fútbol Americano', category: 'DEPORTES' },
  { id: 'dep6', icon: '🏊', name: 'Natación', category: 'DEPORTES' },
  { id: 'dep7', icon: '🚴', name: 'Ciclismo de Ruta', category: 'DEPORTES' },
  { id: 'dep8', icon: '🏃', name: 'Running', category: 'DEPORTES' },
  { id: 'dep9', icon: '🏌️', name: 'Golf', category: 'DEPORTES' },
  { id: 'dep10', icon: '🏓', name: 'Ping Pong', category: 'DEPORTES' },
  { id: 'dep11', icon: '🥋', name: 'Artes Marciales', category: 'DEPORTES' },
  { id: 'dep12', icon: '🛹', name: 'Skateboarding', category: 'DEPORTES' },
  { id: 'dep13', icon: '🥊', name: 'Boxeo', category: 'DEPORTES' },
  { id: 'dep14', icon: '🎯', name: 'Dardos / Tiro al blanco', category: 'DEPORTES' },
  { id: 'dep15', icon: '🎳', name: 'Bowling', category: 'DEPORTES' },
  { id: 'dep16', icon: '⚾', name: 'Béisbol', category: 'DEPORTES' },
  { id: 'dep17', icon: '🏒', name: 'Hockey sobre Hielo', category: 'DEPORTES' },
  { id: 'dep18', icon: '🏑', name: 'Hockey sobre Césped', category: 'DEPORTES' },
  { id: 'dep19', icon: '🏹', name: 'Tiro con Arco', category: 'DEPORTES' },
  { id: 'dep20', icon: '🧗', name: 'Escalada deportiva', category: 'DEPORTES' },
  { id: 'dep21', icon: '🏄', name: 'Surf', category: 'DEPORTES' },
  { id: 'dep22', icon: '🚣', name: 'Remo', category: 'DEPORTES' },
  { id: 'dep23', icon: '⛸️', name: 'Patinaje', category: 'DEPORTES' },
  { id: 'dep24', icon: '🎿', name: 'Esquí', category: 'DEPORTES' },
  { id: 'dep25', icon: '🏎️', name: 'Automovilismo / F1', category: 'DEPORTES' },
  { id: 'dep26', icon: '🏇', name: 'Equitación', category: 'DEPORTES' },
  { id: 'dep27', icon: '🏸', name: 'Bádminton', category: 'DEPORTES' },
  { id: 'dep28', icon: '🛶', name: 'Canotaje / Kayak', category: 'DEPORTES' },
  { id: 'dep29', icon: '🥏', name: 'Frisbee', category: 'DEPORTES' },
  { id: 'dep30', icon: '🏋️', name: 'Halterofilia', category: 'DEPORTES' },

  // PESAS
  { id: 'pes1', icon: '🏋️', name: 'Prensa de Banco (Bench Press)', category: 'PESAS' },
  { id: 'pes2', icon: '🏋️‍♂️', name: 'Peso Muerto (Deadlift)', category: 'PESAS' },
  { id: 'pes3', icon: '🏋️‍♀️', name: 'Sentadilla (Squat)', category: 'PESAS' },
  { id: 'pes4', icon: '💪', name: 'Bíceps con Mancuerna', category: 'PESAS' },
  { id: 'pes5', icon: '🦾', name: 'Tríceps Polea', category: 'PESAS' },
  { id: 'pes6', icon: '🧎', name: 'Prensa de Piernas', category: 'PESAS' },
  { id: 'pes7', icon: '👐', name: 'Remo con Barra (Espalda)', category: 'PESAS' },
  { id: 'pes8', icon: '🏋️', name: 'Prensa Militar (Hombros)', category: 'PESAS' },
  { id: 'pes9', icon: '⚏', name: 'Mancuernas', category: 'PESAS' },
  { id: 'pes10', icon: '🍗', name: 'Día de Piernas (Leg Day)', category: 'PESAS' },

  // CALISTENIA
  { id: 'cal1', icon: '🧗', name: 'Dominada en Barra (Pull-up)', category: 'CALISTENIA' },
  { id: 'cal2', icon: '🤸', name: 'Vertical / Handstand', category: 'CALISTENIA' },
  { id: 'cal3', icon: '🪑', name: 'Fondos en Paralelas (Dips)', category: 'CALISTENIA' },
  { id: 'cal4', icon: '🧘', name: 'Flexiones de Brazo (Push-up)', category: 'CALISTENIA' },
  { id: 'cal5', icon: '🚀', name: 'Muscle-up', category: 'CALISTENIA' },
  { id: 'cal6', icon: '🚩', name: 'Bandera Humana (Human Flag)', category: 'CALISTENIA' },
  { id: 'cal7', icon: '➖', name: 'Plancha Abdominal', category: 'CALISTENIA' },
  { id: 'cal8', icon: '🦵', name: 'Elevación de Piernas colgado', category: 'CALISTENIA' },
  { id: 'cal9', icon: '🛹', name: 'Front Lever', category: 'CALISTENIA' },
  { id: 'cal10', icon: '🤸‍♂️', name: 'Back Lever', category: 'CALISTENIA' },

  // PILATES
  { id: 'pil1', icon: '🛏️', name: 'Reformer (Cama)', category: 'PILATES' },
  { id: 'pil2', icon: '🔵', name: 'Pelota de Pilates', category: 'PILATES' },
  { id: 'pil3', icon: '🧘', name: 'Mat de Pilates', category: 'PILATES' },
  { id: 'pil4', icon: '⭕', name: 'Aro de Pilates', category: 'PILATES' },
  { id: 'pil5', icon: '🦵', name: 'Elevación Lateral de Piernas', category: 'PILATES' },
  { id: 'pil6', icon: '➰', name: 'Estiramiento de Columna', category: 'PILATES' },
  { id: 'pil7', icon: '⚖️', name: 'Clase de Control & Equilibrio', category: 'PILATES' },
  { id: 'pil8', icon: '🤸‍♀️', name: 'Pilates Aéreo', category: 'PILATES' },
  { id: 'pil9', icon: '🧘‍♀️', name: 'Postura del Cisne', category: 'PILATES' },
  { id: 'pil10', icon: '🦵', name: 'El Cien (The Hundred)', category: 'PILATES' },
];

const getStickerCategory = (item) => {
  if (['EMOJIS', 'GYM', 'DEPORTES', 'PESAS', 'CALISTENIA', 'PILATES'].includes(item.category)) {
    return item.category;
  }
  if (item.fileName) {
    if (item.fileName.startsWith('Char_')) {
      return 'LETRAS';
    }
    const zodiacs = ['Aries', 'Cancer', 'Leo', 'Tauro', 'Virgo', 'Geminis', 'Zodiaco_'];
    if (zodiacs.some(z => item.fileName.startsWith(z))) {
      return 'ZODIACO';
    }
  }
  return 'DIBUJOS';
};

const StickerPicker = ({ visible, onClose, onSelect }) => {
  const [activeCategory, setActiveCategory] = React.useState('DIBUJOS');

  const filteredStickers = React.useMemo(() => {
    return STICKERS.filter(item => getStickerCategory(item) === activeCategory);
  }, [activeCategory]);

  return (
    <Modal
      animationType="slide"
      transparent={true}
      visible={visible}
      onRequestClose={onClose}
    >
      <View style={styles.overlay}>
        <TouchableOpacity style={styles.dismiss} onPress={onClose} />
        <View style={styles.content}>
          <View style={styles.header}>
            <View style={styles.handle} />
            <Text style={styles.title}>GALERÍA DE RECURSOS</Text>
          </View>

          {/* Selector de Categorías (Tabs) */}
          <View style={styles.tabsOuterContainer}>
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.tabsContainer}
            >
              {CATEGORIES.map(category => (
                <TouchableOpacity
                  key={category}
                  style={[
                    styles.tabButton,
                    activeCategory === category && styles.activeTabButton
                  ]}
                  onPress={() => setActiveCategory(category)}
                >
                  <Text style={[
                    styles.tabText,
                    activeCategory === category && styles.activeTabText
                  ]}>
                    {category}
                  </Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
          
          <FlatList
            data={filteredStickers}
            numColumns={3}
            keyExtractor={(item) => item.id}
            renderItem={({ item }) => (
              <TouchableOpacity 
                style={styles.stickerItem}
                onPress={() => {
                  onSelect(item);
                  onClose();
                }}
              >
                {item.image ? (
                  <Image source={item.image} style={styles.stickerImage} resizeMode="contain" />
                ) : (
                  <Text style={styles.stickerIcon}>{item.icon}</Text>
                )}
              </TouchableOpacity>
            )}
            contentContainerStyle={styles.list}
          />
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  dismiss: {
    flex: 1,
  },
  content: {
    backgroundColor: '#0D0E12',
    height: height * 0.5,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: '#00E0FF',
    borderBottomWidth: 0,
  },
  header: {
    alignItems: 'center',
    paddingVertical: 15,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: '#333333',
    borderRadius: 2,
    marginBottom: 15,
  },
  title: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 2,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 224, 255, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  list: {
    paddingBottom: 40,
  },
  stickerItem: {
    width: ITEM_WIDTH,
    height: ITEM_WIDTH,
    margin: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 224, 255, 0.2)',
  },
  stickerImage: {
    width: 60,
    height: 60,
  },
  stickerIcon: {
    fontSize: 40,
  },
  tabsOuterContainer: {
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(0, 224, 255, 0.1)',
    marginBottom: 10,
  },
  tabsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTabButton: {
    borderBottomColor: '#00E0FF',
  },
  tabText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#888888',
    letterSpacing: 1.5,
  },
  activeTabText: {
    color: '#00E0FF',
    textShadowColor: 'rgba(0, 224, 255, 0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
});

export default StickerPicker;
