import os
import base64
from PIL import Image

# Directories
script_dir = os.path.dirname(os.path.abspath(__file__))
project_dir = os.path.dirname(script_dir)
stickers_dir = os.path.join(project_dir, "assets", "stickers")
output_js = os.path.join(project_dir, "src", "features", "editor", "StickersBase64.js")

# Create scripts directory if not exists
os.makedirs(os.path.dirname(output_js), exist_ok=True)

js_content = [
    "// Auto-generated by optimize_and_base64_stickers.py",
    "export const STICKERS_BASE64 = {"
]

print("Optimizing stickers and generating base64 mapping...")

count = 0
for filename in sorted(os.listdir(stickers_dir)):
    if not filename.lower().endswith(('.png', '.jpg', '.jpeg')):
        continue
        
    filepath = os.path.join(stickers_dir, filename)
    
    try:
        # Open and resize image
        with Image.open(filepath) as img:
            # Max dimensions
            max_size = 256
            img.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)
            
            # Save back to optimize size
            img.save(filepath, optimize=True, quality=85)
            
        # Read the optimized file and convert to base64
        with open(filepath, "rb") as f:
            encoded_bytes = base64.b64encode(f.read())
            encoded_str = encoded_bytes.decode('utf-8')
            
        # Determine mime type
        mime_type = "image/png" if filename.lower().endswith('.png') else "image/jpeg"
        
        # Add to JS mapping
        # Escaping filename just in case
        js_content.append(f'  "{filename}": "data:{mime_type};base64,{encoded_str}",')
        count += 1
        
    except Exception as e:
        print(f"Error processing {filename}: {e}")

js_content.append("};")

with open(output_js, "w", encoding="utf-8") as f:
    f.write("\n".join(js_content))

print(f"Successfully processed {count} stickers. Base64 file written to {output_js}")
